<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema"
 xmlns:ns="http://www.amsbqa.com/linda16/WSDL1importWSDL2/WSDL2DefineTypes/WSDL2"
 targetNamespace="http://www.amsbqa.com/linda16/WSDL1importWSDL2/WSDL2DefineTypes/WSDL1">
    <import namespace="http://www.amsbqa.com/linda16/WSDL1importWSDL2/WSDL2DefineTypes/WSDL2" location="SubCompany.wsdl"/>
   
    <portType name="PortType">
        <operation name="Operation">
            <input message="ns:Req"/>
            <output message="ns:Res"/>
        </operation>
    </portType>
</definitions>