<?xml version="1.0" encoding="UTF-8"?>
	<!--Created by TIBCO WSDL-->

<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
	xmlns:tns="http://xmlns.example.com/1236046527725" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
	xmlns:ns0="http://www.amsbqa.com/linda19/wsdl2embedsSchema1Schema1includesSchema2"
	name="Untitled" targetNamespace="http://xmlns.example.com/1236046527725">
	
	<wsdl:import
		namespace="http://www.amsbqa.com/linda19/wsdl2embedsSchema1Schema1includesSchema2"
		location="WSDL2embedsSchema1.wsdl" />
	
	<wsdl:service name="WSDL2embedsSchema1-service0">
		<wsdl:port name="NewPortTypeEndpoint0" binding="tns:NewPortTypeEndpoint0Binding">
			<soap:address
				location="http://localhost:8969/19/WSDL2embedsSchema1-service0.serviceagent/NewPortTypeEndpoint0" />
		</wsdl:port>
	</wsdl:service>
	
	<wsdl:binding name="NewPortTypeEndpoint0Binding" type="ns0:NewPortType">
		
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http" />
		
		<wsdl:operation name="QueryContract">
			<soap:operation style="document"
				soapAction="/19/WSDL2embedsSchema1-service0.serviceagent/NewPortTypeEndpoint0/QueryContract" />
			<wsdl:input>
				<soap:body use="literal" parts="BusinessInfo" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="Contract" />
			</wsdl:output>
		</wsdl:operation>
		
		<wsdl:operation name="QueryCompany">
			<soap:operation style="document"
				soapAction="/19/WSDL2embedsSchema1-service0.serviceagent/NewPortTypeEndpoint0/QueryCompany" />
			<wsdl:input>
				<soap:body use="literal" parts="BusinessInfo" />
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal" parts="parameters" />
			</wsdl:output>
		</wsdl:operation>
		
	</wsdl:binding>
	
</wsdl:definitions>