/*
 * Copyright (c) TIBCO Software Inc 2004, 2012. All rights reserved.
 */

package com.tibco.xpd.bom.xsdtransform.utils;

/**
 * 
 * 
 * @author rgreen
 * @since 25 May 2012
 */
public enum XsdTypes {

    STRING, FLOAT, DECIMAL, DOUBLE, INTEGER, INT, BOOLEAN, DATE, TIME, DATETIME, ID, ANYURI, DURATION, BASEBINARY64, HEXBINARY, ANYTYPE, ANYSIMPLETYPE, BYTE, ENTITY, GDAY, GMONTH, GMONTHDAY, GYEAR, GYEARMONTH, IDREF, IDREFS, LANGUAGE, LONG, NAME, NCNAME, NEGATIVEINTEGER, NMTOKEN, NMTOKENS, NONNEGATIVEINTEGER, NONPOSITIVEINTEGER, POSITIVEINTEGER, QNAME, SHORT, TOKEN, UNSIGNEDBYTE, UNSIGNEDINT, UNSIGNEDLONG, UNSIGNEDSHORT

}
