<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
				  xmlns:tibex="http://www.tibco.com/bs3.2/extensions" 
				  xmlns:tns="http://www.example.org/wsinclude/" 
				  xmlns:pref="http://www.example.org/pocommon"
				  xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" 
				  xmlns:xsd="http://www.w3.org/2001/XMLSchema" 
				  name="wsinclude" 
				  targetNamespace="http://www.example.org/wsinclude/" 
				  tibex:bdsSupport="true">
				  
				  
				  <xsd:import namespace="http://www.example.org/pocommon" location="WSDLBOM17_MixedImportsAndIncludes.xsd"/>




				  <wsdl:types>
				  	<xsd:schema
				  		xmlns:xsd="http://www.w3.org/2001/XMLSchema">
				  	<xsd:import
				  		namespace="http://www.example.org/pocommon"
				  		schemaLocation="WSDLBOM17_MixedImportsAndIncludes.xsd">
				  	</xsd:import></xsd:schema></wsdl:types>
				  <wsdl:message name="GetPORequest">    <wsdl:part name="parameter" type="pref:PurchaseOrderType"></wsdl:part>				  </wsdl:message>
  <wsdl:message name="GetPOResponse">
    <wsdl:part name="parameter" type="pref:PurchaseOrderType"></wsdl:part>
  </wsdl:message>
  <wsdl:portType name="wsinclude">
    <wsdl:operation name="GetPO">
      <wsdl:input message="tns:GetPORequest"/>
      <wsdl:output message="tns:GetPOResponse"/>
    </wsdl:operation>
  </wsdl:portType>


</wsdl:definitions>
