<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions
    xmlns="http://example.com/businessobjectmodel" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://example.com/businessobjectmodel">
  <wsdl:types>
    <xsd:schema targetNamespace="http://example.com/businessobjectmodel">
      <xsd:annotation>
        <xsd:documentation>BOMORIGIN::/fds/Business Objects/SingleClassWithOperation.bom</xsd:documentation>
      </xsd:annotation>
      <xsd:complexType id="_8pcjoCmZEd6uG8m8YoWBeg" name="Class1"/>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="testMessage">
  	<wsdl:part name="NewPart" type="xsd:string"></wsdl:part>
  </wsdl:message>
  <wsdl:portType name="Class1">
    <wsdl:operation name="operation1">
    <wsdl:input name="temp" message="testMessage"></wsdl:input>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>