/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.sce.tests.swagger.validation;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;

/**
 * SwaggerCompositeKeywordValidationTest
 * <p>
 * SwaggerCompositeKeywordValidationTest - Test selected validations are correctly raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 *
 * ACE-8631: 7.d - Create validation rule against the use of "oneOf", "anyOf", "allOf", "not" in type declarations in a Swagger file.
 *
 * @author ssirsika
 * @since 17 Oct 2024
 */
public class SwaggerCompositeKeywordValidationTest extends AbstractN2BaseValidationTest {

	public SwaggerCompositeKeywordValidationTest() {
		super(true);
		cleanProjectAtEnd = false;
	}

	/**
     * SwaggerCompositeKeywordValidationTest
     * 
     * @throws Exception
     */
    public void testSwaggerCompositeKeywordValidationTest() throws Exception {
		doTestValidations();
        return;
	}

	@Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos = new ValidationsTestProblemMarkerInfo[] { 
			
        		// Request payload check
			    new ValidationsTestProblemMarkerInfo(
			    		"/SwaggerCompositeKeywordValidationCheck/Process Packages/SwaggerCompositeKeywordValidationCheck.xpdl", //$NON-NLS-1$ 
			    		"ace.unsupportedInputPayloadContent", //$NON-NLS-1$ 
			    		"_5H0TIIxMEe-hrK4YKrpncQ", //$NON-NLS-1$ 
						"BPM  : Unsupported request content: 'oneOf', 'anyOf', 'allOf' and 'not' schema constructs are currently not supported (Employee : Mixed type (unsupported)) (SwaggerCompositeKeywordValidationCheckProcess:CompositeRequest1)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
        		// Request payload check			
			    new ValidationsTestProblemMarkerInfo(
			    		"/SwaggerCompositeKeywordValidationCheck/Process Packages/SwaggerCompositeKeywordValidationCheck.xpdl", //$NON-NLS-1$ 
			    		"ace.unsupportedInputPayloadContent", //$NON-NLS-1$ 
			    		"_C85h4IxNEe-hrK4YKrpncQ", //$NON-NLS-1$ 
						"BPM  : Unsupported request content: 'oneOf', 'anyOf', 'allOf' and 'not' schema constructs are currently not supported (details : Mixed type (unsupported) : oneOf) (SwaggerCompositeKeywordValidationCheckProcess:CompositeRequest2)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
        		// Response payload check
			    new ValidationsTestProblemMarkerInfo(
			    		"/SwaggerCompositeKeywordValidationCheck/Process Packages/SwaggerCompositeKeywordValidationCheck.xpdl", //$NON-NLS-1$ 
			    		"ace.unsupportedOutputPayloadContent", //$NON-NLS-1$ 
			    		"_GTwI8IxNEe-hrK4YKrpncQ", //$NON-NLS-1$ 
						"BPM  : Unsupported response (200) content: 'oneOf', 'anyOf', 'allOf' and 'not' schema constructs are currently not supported (Employee : Mixed type (unsupported))     (SwaggerCompositeKeywordValidationCheckProcess:CompositeResponse1)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
        		// Response payload check
			    new ValidationsTestProblemMarkerInfo(
			    		"/SwaggerCompositeKeywordValidationCheck/Process Packages/SwaggerCompositeKeywordValidationCheck.xpdl", //$NON-NLS-1$ 
			    		"ace.unsupportedOutputPayloadContent", //$NON-NLS-1$ 
			    		"_KSG04IxNEe-hrK4YKrpncQ", //$NON-NLS-1$ 
						"BPM  : Unsupported response (200) content: 'oneOf', 'anyOf', 'allOf' and 'not' schema constructs are currently not supported (details : Mixed type (unsupported) : oneOf)     (SwaggerCompositeKeywordValidationCheckProcess:CompositeResponse2)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
        		// Nested level Request payload check
			    new ValidationsTestProblemMarkerInfo(
			    		"/SwaggerCompositeKeywordValidationCheck/Process Packages/SwaggerCompositeKeywordValidationCheck.xpdl", //$NON-NLS-1$ 
			    		"ace.unsupportedInputPayloadContent", //$NON-NLS-1$ 
			    		"_tuNPYIx0Ee-Y3a0j-Wo-jg", //$NON-NLS-1$ 
						"BPM  : Unsupported request content: 'oneOf', 'anyOf', 'allOf' and 'not' schema constructs are currently not supported (specific : Mixed type (unsupported) : anyOf) (SwaggerCompositeKeywordValidationCheckProcess:CompositeNestedRequest)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
        		// Nested level Response payload check
			    new ValidationsTestProblemMarkerInfo(
			    		"/SwaggerCompositeKeywordValidationCheck/Process Packages/SwaggerCompositeKeywordValidationCheck.xpdl", //$NON-NLS-1$ 
			    		"ace.unsupportedOutputPayloadContent", //$NON-NLS-1$ 
			    		"_uPhzwIx0Ee-Y3a0j-Wo-jg", //$NON-NLS-1$ 
						"BPM  : Unsupported response (200) content: 'oneOf', 'anyOf', 'allOf' and 'not' schema constructs are currently not supported (specific : Mixed type (unsupported) : anyOf)     (SwaggerCompositeKeywordValidationCheckProcess:CompositeNestedResponse)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			                
        };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "SwaggerCompositeKeywordValidationTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.sce.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources = new TestResourceInfo[] {
            new TestResourceInfo("resources/SwaggerCompositeKeywordValidationTest", "SwaggerCompositeKeywordValidationCheck/Process Packages{processes}/SwaggerCompositeKeywordValidationCheck.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
            new TestResourceInfo("resources/SwaggerCompositeKeywordValidationTest", "SwaggerCompositeKeywordValidationCheck/REST Services{rest}/complex.yaml"), //$NON-NLS-1$ //$NON-NLS-2$
        };
    
        return testResources;
    }

}
