package com.tibco.www.bx._2010.debugging.debugger;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

import com.tibco.www.bx._2010.debugging.debuggerType.AddAssertionInput;
import com.tibco.www.bx._2010.debugging.debuggerType.AddTestpointInput;
import com.tibco.www.bx._2010.debugging.debuggerType.EmptyInput;
import com.tibco.www.bx._2010.debugging.debuggerType.OperationFailedFault;
import com.tibco.www.bx._2010.debugging.debuggerType.RemoveAssertionInput;
import com.tibco.www.bx._2010.debugging.debuggerType.RemoveTestpointInput;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.4-b01 Generated
 * source version: 2.2
 * 
 */
@WebService(name = "Tester", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debugger")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Tester {

	/**
	 * 
	 * @param parameters
	 * @return returns boolean
	 * @throws OperationFailedFault
	 */
	@WebMethod(action = "addTestpoint")
	@WebResult(name = "isSuccess", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters")
	public boolean addTestpoint(
			@WebParam(name = "addTestpointInput", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters") AddTestpointInput parameters)
			throws OperationFailedFault;

	/**
	 * 
	 * @param parameters
	 * @return returns boolean
	 * @throws OperationFailedFault
	 */
	@WebMethod(action = "addAssertion")
	@WebResult(name = "isSuccess", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters")
	public boolean addAssertion(
			@WebParam(name = "addAssertionInput", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters") AddAssertionInput parameters)
			throws OperationFailedFault;

	/**
	 * 
	 * @param parameters
	 * @return returns boolean
	 * @throws OperationFailedFault
	 */
	@WebMethod(action = "removeAllAssertions")
	@WebResult(name = "isSuccess", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters")
	public boolean removeAllAssertions(
			@WebParam(name = "emptyInput", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters") EmptyInput parameters)
			throws OperationFailedFault;

	/**
	 * 
	 * @param parameters
	 * @return returns boolean
	 * @throws OperationFailedFault
	 */
	@WebMethod(action = "removeAllTestpoints")
	@WebResult(name = "isSuccess", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters")
	public boolean removeAllTestpoints(
			@WebParam(name = "emptyInput", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters") EmptyInput parameters)
			throws OperationFailedFault;

	/**
	 * 
	 * @param parameters
	 * @return returns boolean
	 * @throws OperationFailedFault
	 */
	@WebMethod(action = "removeAssertion")
	@WebResult(name = "isSuccess", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters")
	public boolean removeAssertion(
			@WebParam(name = "removeAssertionInput", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters") RemoveAssertionInput parameters)
			throws OperationFailedFault;

	/**
	 * 
	 * @param parameters
	 * @return returns boolean
	 * @throws OperationFailedFault
	 */
	@WebMethod(action = "removeTestpoint")
	@WebResult(name = "isSuccess", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters")
	public boolean removeTestpoint(
			@WebParam(name = "removeTestpointInput", targetNamespace = "http://www.tibco.com/bx/2010/debugging/debuggerType", partName = "parameters") RemoveTestpointInput parameters)
			throws OperationFailedFault;

}
