/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import java.math.BigInteger;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.ConstantPeriod}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ConstantPeriodValidator {
    boolean validate();

    boolean validateDays(BigInteger value);

    boolean validateHours(BigInteger value);

    boolean validateMicroSeconds(BigInteger value);

    boolean validateMinutes(BigInteger value);

    boolean validateMonths(BigInteger value);

    boolean validateSeconds(BigInteger value);

    boolean validateWeeks(BigInteger value);

    boolean validateYears(BigInteger value);
}
