/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import com.tibco.xpd.xpdl2.Expression;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.MultiInstanceScripts}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MultiInstanceScriptsValidator {
    boolean validate();

    boolean validateLoopExpression(Expression value);

    boolean validateComplexExitExpression(Expression value);

    boolean validateAdditionalInstances(Expression value);
}
