/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import com.tibco.xpd.xpdl2.ExternalReference;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.PortTypeOperation}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PortTypeOperationValidator {
    boolean validate();

    boolean validatePortTypeName(String value);

    boolean validateOperationName(String value);

    boolean validateExternalReference(ExternalReference value);

    boolean validateTransport(String value);
}
