/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import com.tibco.xpd.xpdl2.DataMapping;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.TransformScript}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TransformScriptValidator {
    boolean validate();

    boolean validateDataMappings(EList<DataMapping> value);

    boolean validateInputDom(EList<String> value);

    boolean validateOutputDom(EList<String> value);

    boolean validateInputDom(String value);

    boolean validateOutputDom(String value);
}
