<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns="http://www.amsbqa.com/linda21/WSDL1ImportWSDL2/wsdl2embedSchema1/WSDL2EmbedSchema1/Schema1includeSchema2/Schema.xsd" xmlns:tns="http://www.amsbqa.com/linda21/WSDL1ImportWSDL2/wsdl2embedSchema1/WSDL2EmbedSchema1/Schema1includeSchema2/WSDL2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.amsbqa.com/linda21/WSDL1ImportWSDL2/wsdl2embedSchema1/WSDL2EmbedSchema1/Schema1includeSchema2/WSDL2">
    <import namespace="http://www.amsbqa.com/linda21/WSDL1ImportWSDL2/wsdl2embedSchema1/WSDL2EmbedSchema1/Schema1includeSchema2/Schema.xsd" location="SecondIncludeSchema.xsd"/>
    <message name="Message">
        <part name="part1" element="ns:Info"/>
    </message>
    <message name="Message1">
        <part name="part1" element="ns:ResInfo"/>
    </message>
</definitions>