<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://www.amsbqa.com/Linda22/WSDL1ImportWSDL2/WSDL2ImportSchema/WSDL2" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="urn:xmlns:beb.ameritrade.com" targetNamespace="http://www.amsbqa.com/Linda22/WSDL1ImportWSDL2/WSDL2ImportSchema/WSDL2">
    <import namespace="urn:xmlns:beb.ameritrade.com" location="Schema/common-messages.xsd"/>
    <types/>
    <message name="Message">
        <part name="part1" element="ns:GroupID"/>
    </message>
</definitions>