<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://www.tibco.com/bs3.0/_-HuaMVclEd6o6c8LFxdK_A" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="UC1CaWebServiceInvoke" targetNamespace="http://www.tibco.com/bs3.0/_-HuaMVclEd6o6c8LFxdK_A" tibex:XPDL="UC1CaWebServiceInvoke.xpdl">
  <wsdl:types>
    <xsd:schema xmlns="http://www.tibco.com/bs3.0/_-HuaMVclEd6o6c8LFxdK_A" targetNamespace="http://www.tibco.com/bs3.0/_-HuaMVclEd6o6c8LFxdK_A"/>
  </wsdl:types>
  <wsdl:message name="UC1CaWSInvoke_StartEvent_INPUT"/>
  <wsdl:portType name="UC1CaWSInvoke" tibex:FlowContainer="_-HuaMFclEd6o6c8LFxdK_A">
    <wsdl:operation name="StartEvent">
      <wsdl:input message="ns:UC1CaWSInvoke_StartEvent_INPUT" tibex:Event="_Iz_IlVcmEd6o6c8LFxdK_A"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
