/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import org.eclipse.emf.common.util.EList;

import com.tibco.xpd.xpdExtension.AllocationStrategy;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.ActivityResourcePatterns}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ActivityResourcePatternsValidator {
    boolean validate();

    boolean validateAllocationStrategy(AllocationStrategy value);

    boolean validateAllocationStrategy(EList value);
}
