/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.ApplicationType;
import com.tibco.xpd.xpdl2.ExternalReference;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Application}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ApplicationValidator {
    boolean validate();

    boolean validateType(ApplicationType value);

    boolean validateExternalReference(ExternalReference value);
}
