/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.ExceptionName;
import com.tibco.xpd.xpdl2.ExecutionType;
import com.tibco.xpd.xpdl2.Expression;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Deadline}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeadlineValidator {
    boolean validate();

    boolean validateDeadlineDuration(Expression value);

    boolean validateExceptionName(ExceptionName value);

    boolean validateExecution(ExecutionType value);
}
