/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.ExtendedAttribute}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ExtendedAttributeValidator {
    boolean validate();

    boolean validateMixed(FeatureMap value);

    boolean validateGroup(FeatureMap value);

    boolean validateAny(FeatureMap value);

    boolean validateName(String value);

    boolean validateValue(String value);
}
