/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.ecore.util.FeatureMap;

import com.tibco.xpd.xpdl2.ImplementationType;
import com.tibco.xpd.xpdl2.ResultError;
import com.tibco.xpd.xpdl2.TriggerConditional;
import com.tibco.xpd.xpdl2.TriggerIntermediateMultiple;
import com.tibco.xpd.xpdl2.TriggerResultCancel;
import com.tibco.xpd.xpdl2.TriggerResultCompensation;
import com.tibco.xpd.xpdl2.TriggerResultLink;
import com.tibco.xpd.xpdl2.TriggerResultMessage;
import com.tibco.xpd.xpdl2.TriggerTimer;
import com.tibco.xpd.xpdl2.TriggerType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.IntermediateEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface IntermediateEventValidator {
    boolean validate();

    boolean validateTriggerResultMessage(TriggerResultMessage value);

    boolean validateTriggerTimer(TriggerTimer value);

    boolean validateResultError(ResultError value);

    boolean validateTriggerResultCompensation(TriggerResultCompensation value);

    boolean validateTriggerConditional(TriggerConditional value);

    boolean validateTriggerResultLink(TriggerResultLink value);

    boolean validateTriggerIntermediateMultiple(
            TriggerIntermediateMultiple value);

    boolean validateImplementation(ImplementationType value);

    boolean validateTarget(String value);

    boolean validateTrigger(TriggerType value);

    boolean validateAnyAttribute(FeatureMap value);

    boolean validateTriggerResultCancel(TriggerResultCancel value);
}
