/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.common.util.EList;

import com.tibco.xpd.xpdl2.Performers;
import com.tibco.xpd.xpdl2.Pool;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Lane}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LaneValidator {
    boolean validate();

    boolean validateObject(com.tibco.xpd.xpdl2.Object value);

    boolean validateParentLane(String value);

    boolean validateParentPoolId(String value);

    boolean validateParentPool(Pool value);

    boolean validatePerformers(Performers value);

    boolean validateNestedLane(EList value);
}
