/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import java.math.BigInteger;

import com.tibco.xpd.xpdl2.Expression;
import com.tibco.xpd.xpdl2.TestTimeType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.LoopStandard}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopStandardValidator {
    boolean validate();

    boolean validateLoopCondition(String value);

    boolean validateLoopCounter(BigInteger value);

    boolean validateLoopMaximum(BigInteger value);

    boolean validateTestTime(TestTimeType value);

    boolean validateLoopCondition(Expression value);
}
