/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import java.math.BigInteger;

import com.tibco.xpd.xpdl2.Expression;
import com.tibco.xpd.xpdl2.MIFlowConditionType;
import com.tibco.xpd.xpdl2.MIOrderingType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.LoopMultiInstance}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface LoopMultiInstanceValidator {
    boolean validate();

    boolean validateComplexMIFlowCondition(String value);

    boolean validateLoopCounter(BigInteger value);

    boolean validateMICondition(String value);

    boolean validateMIFlowCondition(MIFlowConditionType value);

    boolean validateMIOrdering(MIOrderingType value);

    boolean validateMICondition(Expression value);

    boolean validateComplexMIFlowCondition(Expression value);
}
