/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.Message;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.MessageFlow}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MessageFlowValidator {
    boolean validate();

    boolean validateMessage(Message value);

    boolean validateObject(com.tibco.xpd.xpdl2.Object value);

    boolean validateSource(String value);

    boolean validateTarget(String value);

    boolean validatePackage(com.tibco.xpd.xpdl2.Package value);
}
