/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.Category;
import com.tibco.xpd.xpdl2.Documentation;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Object}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ObjectValidator {
    boolean validate();

    boolean validateCategories(Category value);

    boolean validateDocumentation(Documentation value);
}
