/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.common.util.EList;

import com.tibco.xpd.xpdl2.ExclusiveType;
import com.tibco.xpd.xpdl2.GatewayType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Split}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface SplitValidator {
    boolean validate();

    boolean validateTransitionRefs(EList value);

    boolean validateOutgoingCondition(String value);

    boolean validateType(GatewayType value);

    boolean validateExclusiveType(ExclusiveType value);
}
