/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.ImplementationType;
import com.tibco.xpd.xpdl2.TriggerConditional;
import com.tibco.xpd.xpdl2.TriggerMultiple;
import com.tibco.xpd.xpdl2.TriggerResultLink;
import com.tibco.xpd.xpdl2.TriggerResultMessage;
import com.tibco.xpd.xpdl2.TriggerResultSignal;
import com.tibco.xpd.xpdl2.TriggerTimer;
import com.tibco.xpd.xpdl2.TriggerType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.StartEvent}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StartEventValidator {
    boolean validate();

    boolean validateTriggerResultMessage(TriggerResultMessage value);

    boolean validateTriggerTimer(TriggerTimer value);

    boolean validateTriggerConditional(TriggerConditional value);

    boolean validateTriggerResultSignal(TriggerResultSignal value);

    boolean validateTriggerResultLink(TriggerResultLink value);

    boolean validateTriggerMultiple(TriggerMultiple value);

    boolean validateImplementation(ImplementationType value);

    boolean validateTrigger(TriggerType value);
}
