/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.ResultError;
import com.tibco.xpd.xpdl2.TriggerConditional;
import com.tibco.xpd.xpdl2.TriggerResultCompensation;
import com.tibco.xpd.xpdl2.TriggerResultLink;
import com.tibco.xpd.xpdl2.TriggerResultMessage;
import com.tibco.xpd.xpdl2.TriggerTimer;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.TriggerIntermediateMultiple}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TriggerIntermediateMultipleValidator {
    boolean validate();

    boolean validateTriggerResultMessage(TriggerResultMessage value);

    boolean validateTriggerTimer(TriggerTimer value);

    boolean validateResultError(ResultError value);

    boolean validateTriggerResultCompensation(TriggerResultCompensation value);

    boolean validateTriggerConditional(TriggerConditional value);

    boolean validateTriggerResultLink(TriggerResultLink value);
}
