<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="http://www.amsbqa.com/linda03/XSD1IncludesXSD2/BothDefineTypes/wsdl" xmlns:ns="http://www.amsbqa.com/linda03/XSD1IncludesXSD2_Both_Define_Types03/" targetNamespace="http://www.amsbqa.com/linda03/XSD1IncludesXSD2/BothDefineTypes/wsdl">
    <import namespace="http://www.amsbqa.com/linda03/XSD1IncludesXSD2_Both_Define_Types03/" location="Foo_XSD1includingXSD2.xsd"/>
    <message name="Request">
        <part name="part1" type="ns:fooType"/>
    </message>
    <message name="Response">
        <part name="part1" element="ns:Info"/>
    </message>
    <message name="Fault">
        <part name="part1" element="ns:Name"/>
    </message>
    <portType name="Foo">
        <operation name="Operation">
            <input message="tns:Request"/>
            <output message="tns:Response"/>
            <fault name="fault1" message="tns:Fault"/>
        </operation>
    </portType>
</definitions>