<?xml version="1.0" encoding="UTF-8"?>
<!--Created by TIBCO WSDL-->
<wsdl:definitions xmlns:ns="http://www.amsbqa.com/Linda10/Schema1importSchema2/Schema2" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://www.amsbqa.com/Linda10/Schema1importSchema2/WSDL/OperationImpl/WSDLEmbedSchema1__WSDLEmbedSchame2__Schema1IncludeSchma2__BothDefineTypes10" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" name="Untitled" targetNamespace="http://www.amsbqa.com/Linda10/Schema1importSchema2/WSDL/OperationImpl/WSDLEmbedSchema1__WSDLEmbedSchame2__Schema1IncludeSchma2__BothDefineTypes10">
    <wsdl:import namespace="http://www.amsbqa.com/Linda10/Schema1importSchema2/Schema2" location="ProfileSchema.xsd"/>
    <wsdl:types>
        <xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.amsbqa.com/Linda10/Schema1importSchema2/Schema2">
            <xs:include schemaLocation="profile/CarUserProfile.xsd"/>
        </xs:schema>
    </wsdl:types>
    <wsdl:portType name="PortType">
        <wsdl:operation name="Operation">
            <wsdl:input message="tns:Subscribe"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:message name="Subscribe">
        <wsdl:part name="part1" element="ns:CarBaeInfo"/>
    </wsdl:message>
</wsdl:definitions>