<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:ns0="http://tibco.com/amx/integration/test/wsdl/porttype" xmlns:tns="http://tibco.com/amx/integration/test/wsdl/messages" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MessageWSDL" targetNamespace="http://tibco.com/amx/integration/test/wsdl/messages">
    <import location="FirstImportSchema.xsd" namespace="http://tibco.com/amx/integration/test/wsdl/porttype"/>
    <message name="WsdlImport_InMsg">
        <part name="PurchaseOrderRequest_Type" type="ns0:CT_PurchaseOrderRequest"/>
    </message>
    <message name="WsdlImport_OutMsg">
        <part name="PurchaseOrderResponse_Type" type="ns0:CT_PurchaseOrderResponse"/>
    </message>
</definitions>