<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:tns="http://www.amsbqa.com/Linda05/WSDLDefineTypes/WSDL" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.amsbqa.com/Linda05/WSDLDefineTypes/WSDL" tibex:src="file:/C:/StudioInstallation/EnggBuildInstl/05/05/Genric_WSDL_Define_Types.wsdl">
    <types/>
    <!-- Input output Messages for operations -->
    <message name="alltypes">
        <part name="teststring" type="xsd:string"/>
        <part name="testnormalizedString" type="xsd:normalizedString"/>
        <part name="testtoken" type="xsd:token"/>
        <part name="testlanguage" type="xsd:language"/>
        <part name="testName" type="xsd:Name"/>
        <part name="testNCName" type="xsd:NCName"/>
        <part name="testQName" type="xsd:QName"/>
        <part name="testNMToken" type="xsd:NMTOKEN"/>
        <part name="testpart1" type="xsd:NMTOKENS"/>
        <part name="testID" type="xsd:ID"/>
        <part name="testIDREF" type="xsd:IDREF"/>
        <part name="testIDREFS" type="xsd:IDREFS"/>
        <part name="testENTITY" type="xsd:ENTITY"/>
        <part name="testENTITIES" type="xsd:ENTITIES"/>
        <part name="testByte" type="xsd:byte"/>
        <part name="testShort" type="xsd:short"/>
        <part name="testInt" type="xsd:int"/>
        <part name="testLong" type="xsd:long"/>
        <part name="testUnSignedByte" type="xsd:unsignedByte"/>
        <part name="testUnSignedShort" type="xsd:unsignedShort"/>
        <part name="UnSignedInt" type="xsd:unsignedInt"/>
        <part name="testUnSignedLong" type="xsd:unsignedLong"/>
        <part name="testInteger" type="xsd:integer"/>
        <part name="testPositiveInteger" type="xsd:positiveInteger"/>
        <part name="testNegativeInteger" type="xsd:negativeInteger"/>
        <part name="testnonPositiveInteger" type="xsd:nonPositiveInteger"/>
        <part name="testnonNegativeInteger" type="xsd:nonNegativeInteger"/>
        <part name="testfloat" type="xsd:float"/>
        <part name="testdouble" type="xsd:double"/>
        <part name="testdecimal" type="xsd:decimal"/>
        <part name="testboolean" type="xsd:boolean"/>
        <part name="testtime" type="xsd:time"/>
        <part name="testdate" type="xsd:date"/>
        <part name="testdateTime" type="xsd:dateTime"/>
        <part name="testday" type="xsd:gDay"/>
        <part name="testmonth" type="xsd:gMonth"/>
        <part name="testyear" type="xsd:gYear"/>
        <part name="testyearMonth" type="xsd:gYearMonth"/>
        <part name="testmonthDay" type="xsd:gMonthDay"/>
        <!-- <part name="testbase64" type="xsd:base64Binary"/>
        <part name="testhexBinary" type="xsd:hexBinary"/>-->
    </message>
    <message name="outmessage">
    	<part name="teststring" type="xsd:string"/>
    </message>
    <portType name="StringGenerics">
        <operation name="testAllTypes">
            <input message="tns:alltypes" name="inMessageSG1"/>
            <output message="tns:outmessage" name="OutMessageSG1"/>
        </operation>
     </portType>
</definitions>
