/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.common.util.EList;

import com.tibco.xpd.xpdl2.Category;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Group}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface GroupValidator {
    boolean validate();

    boolean validateCategory(Category value);

    boolean validateObject(EList value);
}
