/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.ecore.util.FeatureMap;

import com.tibco.xpd.xpdl2.ArrayType;
import com.tibco.xpd.xpdl2.BasicType;
import com.tibco.xpd.xpdl2.DeclaredType;
import com.tibco.xpd.xpdl2.EnumerationType;
import com.tibco.xpd.xpdl2.ExternalReference;
import com.tibco.xpd.xpdl2.ListType;
import com.tibco.xpd.xpdl2.RecordType;
import com.tibco.xpd.xpdl2.Schema;
import com.tibco.xpd.xpdl2.UnionType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Member}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MemberValidator {
    boolean validate();

    boolean validateBasicType(BasicType value);

    boolean validateDeclaredType(DeclaredType value);

    boolean validateSchemaType(Schema value);

    boolean validateExternalReference(ExternalReference value);

    boolean validateRecordType(RecordType value);

    boolean validateUnionType(UnionType value);

    boolean validateEnumerationType(EnumerationType value);

    boolean validateArrayType(ArrayType value);

    boolean validateListType(ListType value);

    boolean validateAnyAttribute(FeatureMap value);
}
