/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.common.util.EMap;
import org.eclipse.emf.ecore.util.FeatureMap;

import com.tibco.xpd.xpdl2.ConformanceClass;
import com.tibco.xpd.xpdl2.PackageHeader;
import com.tibco.xpd.xpdl2.RedefinableHeader;
import com.tibco.xpd.xpdl2.Script;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Package}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PackageValidator {
    boolean validate();

    boolean validatePackageHeader(PackageHeader value);

    boolean validateRedefinableHeader(RedefinableHeader value);

    boolean validateConformanceClass(ConformanceClass value);

    boolean validateScript(Script value);

    boolean validateExternalPackages(EList value);

    boolean validateTypeDeclarations(EList value);

    boolean validatePartnerLinkTypes(EList value);

    boolean validatePools(EList value);

    boolean validateMessageFlows(EList value);

    boolean validateAssociations(EList value);

    boolean validateArtifacts(EList value);

    boolean validateProcesses(EList value);

    boolean validateXSISchemaLocation(EMap value);

    boolean validateMixed(FeatureMap value);

    boolean validateGroup(FeatureMap value);

    boolean validateAny(FeatureMap value);
}
