/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import org.eclipse.emf.common.util.EList;

import com.tibco.xpd.xpdl2.WebServiceOperation;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.WebServiceApplication}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface WebServiceApplicationValidator {
    boolean validate();

    boolean validateWebServiceOperation(WebServiceOperation value);

    boolean validateWebServiceFaultCatch(EList value);

    boolean validateInputMsgName(String value);

    boolean validateOutputMsgName(String value);
}
