/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.process.analyst.api.test.utils;

import org.eclipse.core.runtime.Platform;
import org.osgi.framework.Bundle;
import com.tibco.xpd.core.test.util.classapi.AbstractApiClassTest;

/**
 * Xpdl2ModelUtilApiTest
 * <p>
 * Xpdl2ModelUtilApiTest - To test ongoing backwards-compatibility of API provided by the class(es):
 * <li>com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil</li> 
 * </p>
 *
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 */
public class Xpdl2ModelUtilApiTest extends AbstractApiClassTest {

    public void testApiFor_com_tibco_xpd_xpdl2_util_Xpdl2ModelUtil() throws Exception {

		String clazzBundleId = "com.tibco.xpd.xpdl2.edit"; //$NON-NLS-1$

		Bundle clazzBundle = Platform.getBundle(clazzBundleId);
		assertNotNull("Could not load the API-class parent plug-in bundle: " + clazzBundleId, clazzBundle); //$NON-NLS-1$
		

        String clazzName = "com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil"; //$NON-NLS-1$

        Class<?> clazz = clazzBundle.loadClass(clazzName);

        assertNotNull("Failed to load API-class to test: " + clazzName, clazz);  //$NON-NLS-1$

        AbstractApiClassTest.log(clazz.toString());

        String[] constructorControlSample = new String[] { 
            "public com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil()", //$NON-NLS-1$
                };
        checkApiConstructors(clazz, constructorControlSample);

        String[] fieldControlSample = new String[] { 
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.STUDIO_SPECIFIC_TOOL_ID",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.CONNECTION_INFO_IDSUFFIX",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.START_ANCHOR_IDSUFFIX",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.END_ANCHOR_IDSUFFIX",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.LABEL_ANCHOR_IDSUFFIX",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.LABEL_SIZE_IDSUFFIX",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.BORDER_EVENTPOS_IDSUFFIX",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.DEFAULT_WORK_ITEM_PRIORITY",  //$NON-NLS-1$  
            "public static final java.lang.String com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil.GENERATED_SERVICE_TARGETNS_PREFIX",  //$NON-NLS-1$ 
                };
        checkApiFields(clazz, fieldControlSample);

        String[] methodControlSample = new String[] { 
            "public static com.tibco.xpd.xpdl2.Package getPackage(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static java.lang.String getDisplayName(com.tibco.xpd.xpdl2.NamedElement)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.ecore.EObject getContainer(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.ecore.EObject getAncestor(org.eclipse.emf.ecore.EObject,java.lang.Class)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Participant getParticipant(com.tibco.xpd.xpdl2.Process,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Expression createExpression(java.lang.String)", //$NON-NLS-1$ 
            "public static java.lang.Boolean isEventImplemented(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.lang.Object getOtherElement(com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.WebServiceOperation getWebServiceOperation(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.PortTypeOperation getPortTypeOperation(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ConnectorGraphicsInfo getConnectorGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalConnector,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ConnectorGraphicsInfo getConnectorGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalConnector)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Lane getLane(com.tibco.xpd.xpdl2.Process,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.NodeGraphicsInfo getNodeGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalNode)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.NodeGraphicsInfo getNodeGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalNode,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Process getProcess(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.DataMapping> getDataMappings(com.tibco.xpd.xpdl2.Activity,com.tibco.xpd.xpdl2.DirectionType)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Pool getParentPool(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.Transition> getOutgoingTransitions(java.lang.String,com.tibco.xpd.xpdl2.FlowContainer)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.Transition> getIncomingTransitions(java.lang.String,com.tibco.xpd.xpdl2.FlowContainer)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.TransformScript getTransformScript(com.tibco.xpd.xpdl2.TaskScript)", //$NON-NLS-1$ 
            "public static boolean isTaskLibrary(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static boolean isPageflow(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.lang.Object getOtherAttribute(com.tibco.xpd.xpdl2.OtherAttributesContainer,org.eclipse.emf.ecore.EStructuralFeature)", //$NON-NLS-1$ 
            "public static java.lang.String getDisplayNameOrName(com.tibco.xpd.xpdl2.NamedElement)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.Lane> getProcessLanes(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Activity> getAllActivitiesInProc(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.lang.String getActivityImagePath(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Activity getActivityById(com.tibco.xpd.xpdl2.Process,java.lang.String)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.common.command.Command getSetOtherElementCommand(org.eclipse.emf.edit.domain.EditingDomain,com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.common.command.Command getSetOtherAttributeCommand(org.eclipse.emf.edit.domain.EditingDomain,com.tibco.xpd.xpdl2.OtherAttributesContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.ecore.EObject getDuplicateNameObject(org.eclipse.emf.ecore.EObject,org.eclipse.emf.ecore.EObject,java.lang.String)", //$NON-NLS-1$ 
            "public static java.lang.String setEndpointFromDataPickerSelection(java.lang.Object,com.tibco.xpd.xpdl2.WebServiceOperation)", //$NON-NLS-1$ 
            "public static void setOtherAttribute(com.tibco.xpd.xpdl2.OtherAttributesContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Activity getParentActivity(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ProcessRelevantData resolveParameter(com.tibco.xpd.xpdl2.Activity,java.lang.String)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.common.command.Command getRemoveOtherElementCommand(org.eclipse.emf.edit.domain.EditingDomain,com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.common.command.Command getSetEndpointFromDataPickerSelectionCommand(org.eclipse.emf.edit.domain.EditingDomain,java.lang.Object,com.tibco.xpd.xpdl2.WebServiceOperation)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.NodeGraphicsInfo getOrCreateNodeGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalNode,org.eclipse.emf.edit.domain.EditingDomain,org.eclipse.emf.common.command.CompoundCommand,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.NodeGraphicsInfo getOrCreateNodeGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalNode,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.NodeGraphicsInfo getOrCreateNodeGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalNode)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.NodeGraphicsInfo getOrCreateNodeGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalNode,org.eclipse.emf.edit.domain.EditingDomain,org.eclipse.emf.common.command.CompoundCommand)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Pool> getProcessPools(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.lang.Object getParticipantOrProcessData(com.tibco.xpd.xpdl2.Process,com.tibco.xpd.xpdl2.Performer)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.common.util.EList getOtherElementList(com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature)", //$NON-NLS-1$ 
            "public static boolean isProcessAPIActivity(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.lang.String getUniqueDisplayNameInSet(java.lang.String,java.util.Collection<? extends com.tibco.xpd.xpdl2.NamedElement>,boolean)", //$NON-NLS-1$ 
            "public static java.lang.String getUniqueDisplayNameInSet(java.lang.String,java.util.Collection<? extends com.tibco.xpd.xpdl2.NamedElement>)", //$NON-NLS-1$ 
            "public static void setOtherElement(com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static boolean getOtherAttributeAsBoolean(com.tibco.xpd.xpdl2.OtherAttributesContainer,org.eclipse.emf.ecore.EStructuralFeature)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.DataType resolveDataType(com.tibco.xpd.xpdl2.Package,com.tibco.xpd.xpdl2.DataType,boolean)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.JoinSplitType safeGetGatewayType(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ExclusiveType safeGetExclusiveType(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static boolean isCorrelationActivity(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Activity> getAttachedEvents(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.DataField> getCorrelationDataFields(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static boolean isWsdlDerived(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static boolean isGeneratedRequestActivity(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static boolean isEventAttachedToTask(java.lang.Object)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ProcessRelevantData getDuplicateDisplayFieldOrParam(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.ProcessRelevantData,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Participant getDuplicateDisplayParticipant(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.Participant,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.TypeDeclaration getDuplicateDisplayTypeDeclaration(com.tibco.xpd.xpdl2.Package,com.tibco.xpd.xpdl2.TypeDeclaration,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.ProcessInterface getDuplicateDisplayProcessInterface(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdExtension.ProcessInterface,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.StartMethod getDuplicateDisplayStartMethod(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.NamedElement,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.IntermediateMethod getDuplicateDisplayIntermediateMethod(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.NamedElement,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Process getDuplicateDisplayNameProcess(com.tibco.xpd.xpdl2.Package,com.tibco.xpd.xpdl2.Process,java.lang.String)", //$NON-NLS-1$ 
            "public static java.util.Collection<org.eclipse.emf.ecore.EObject> getAllNodesInEmbeddedSubProc(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static boolean isMessageProcessStartActivity(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Association> getAllAssociationsInProc(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.MessageFlow> getAllMessageFlowsInProc(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Activity getEmbSubProcActivityForActSet(com.tibco.xpd.xpdl2.Process,java.lang.String)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.DataField> getAssociatedCorrelationData(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Artifact> getAllArtifactsInProcess(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Transition> getAllTransitionsInProc(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.util.Collection<org.eclipse.core.resources.IProject> getAllReferencedProjects(org.eclipse.core.resources.IProject)", //$NON-NLS-1$ 
            "public static void addOtherElement(com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.common.command.Command getAddOtherElementCommand(org.eclipse.emf.edit.domain.EditingDomain,com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static void removeOtherElement(com.tibco.xpd.xpdl2.OtherElementsContainer,org.eclipse.emf.ecore.EStructuralFeature,java.lang.Object)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ConnectorGraphicsInfo getOrCreateConnectorGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalConnector)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ConnectorGraphicsInfo getOrCreateConnectorGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalConnector,org.eclipse.emf.edit.domain.EditingDomain,org.eclipse.emf.common.command.CompoundCommand)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ConnectorGraphicsInfo getOrCreateConnectorGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalConnector,org.eclipse.emf.edit.domain.EditingDomain,org.eclipse.emf.common.command.CompoundCommand,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ConnectorGraphicsInfo getOrCreateConnectorGraphicsInfo(com.tibco.xpd.xpdl2.GraphicalConnector,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Lane getActivitySetParentLane(com.tibco.xpd.xpdl2.ActivitySet)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ActivitySet getEmbeddedSubProcessActivitySet(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.ActivitySet> getEmbeddedSubProcessesTree(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Activity> getAllActivitiesInEmbeddedSubProc(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.Collection<com.tibco.xpd.xpdl2.Transition> getAllTransitionsInEmbeddedSubProc(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.util.Collection<org.eclipse.emf.ecore.EObject> getAllNodesInPool(com.tibco.xpd.xpdl2.Pool)", //$NON-NLS-1$ 
            "public static java.util.Collection<org.eclipse.emf.ecore.EObject> getAllNodesInLane(com.tibco.xpd.xpdl2.Lane)", //$NON-NLS-1$ 
            "public static java.util.Collection<org.eclipse.emf.ecore.EObject> getAllSelectedActivitiesAndTransitions(java.util.Collection<org.eclipse.emf.ecore.EObject>,boolean,boolean)", //$NON-NLS-1$ 
            "public static java.util.Collection<org.eclipse.emf.ecore.EObject> getObjectConnections(java.util.Collection<org.eclipse.emf.ecore.EObject>,boolean,boolean)", //$NON-NLS-1$ 
            "public static org.eclipse.swt.graphics.Rectangle getObjectBounds(com.tibco.xpd.xpdl2.GraphicalNode)", //$NON-NLS-1$ 
            "public static java.util.Map<java.lang.String, org.eclipse.emf.ecore.EObject> reassignUniqueIds(java.util.Collection,org.eclipse.emf.edit.domain.EditingDomain,java.lang.String)", //$NON-NLS-1$ 
            "public static java.util.Map<java.lang.String, org.eclipse.emf.ecore.EObject> reassignUniqueIds(java.util.Collection,org.eclipse.emf.edit.domain.EditingDomain)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.ProcessRelevantData getDuplicateFieldOrParam(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.ProcessRelevantData,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Participant getDuplicateParticipant(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.Participant,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.TypeDeclaration getDuplicateTypeDeclaration(com.tibco.xpd.xpdl2.Package,com.tibco.xpd.xpdl2.TypeDeclaration,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Process getDuplicateProcess(com.tibco.xpd.xpdl2.Package,com.tibco.xpd.xpdl2.Process,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.ProcessInterface getDuplicateProcessInterface(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdExtension.ProcessInterface,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.StartMethod getDuplicateStartMethod(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.NamedElement,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.ErrorMethod getDuplicateError(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdExtension.ErrorMethod,java.lang.String)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdExtension.IntermediateMethod getDuplicateIntermediateMethod(org.eclipse.emf.ecore.EObject,com.tibco.xpd.xpdl2.NamedElement,java.lang.String)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.ecore.EObject createEObjectCopy(org.eclipse.emf.edit.domain.EditingDomain,org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static java.util.Collection<org.eclipse.emf.ecore.EObject> createEObjectsCopy(org.eclipse.emf.edit.domain.EditingDomain,java.util.Collection<org.eclipse.emf.ecore.EObject>)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.DataMapping> getMessageMappings(com.tibco.xpd.xpdl2.Message)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.DataMapping> getScriptTaskDataMappings(com.tibco.xpd.xpdl2.TaskScript)", //$NON-NLS-1$ 
            "public static java.lang.String getEnumLocalisedName(org.eclipse.emf.ecore.EEnumLiteral)", //$NON-NLS-1$ 
            "public static java.lang.String getReferencedGatewayActivityId(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.ecore.EObject getDuplicateDisplayNameObject(org.eclipse.emf.ecore.EObject,org.eclipse.emf.ecore.EObject,java.lang.String)", //$NON-NLS-1$ 
            "public static boolean shouldHaveDisplayName(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static boolean shouldHaveTokenName(org.eclipse.emf.ecore.EObject)", //$NON-NLS-1$ 
            "public static java.lang.String getNamedElementLabelText(com.tibco.xpd.xpdl2.NamedElement)", //$NON-NLS-1$ 
            "public static org.eclipse.emf.ecore.EObject resolveUri(org.eclipse.emf.common.util.URI)", //$NON-NLS-1$ 
            "public static boolean isTaskReceiveGenerated(com.tibco.xpd.xpdl2.TaskReceive)", //$NON-NLS-1$ 
            "public static java.lang.String getWsdlFileName(java.lang.String)", //$NON-NLS-1$ 
            "public static org.eclipse.core.resources.IFile getDerivedWsdlFile(org.eclipse.core.resources.IFile)", //$NON-NLS-1$ 
            "public static java.lang.String getDerivedWsdlNamespace(com.tibco.xpd.xpdl2.Package)", //$NON-NLS-1$ 
            "public static boolean executeCommandOutsideTransaction(org.eclipse.emf.edit.domain.EditingDomain,org.eclipse.emf.common.command.Command)", //$NON-NLS-1$ 
            "public static java.util.List<com.tibco.xpd.xpdl2.Activity> getStartEventsForProcess(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "public static java.lang.String getWebServiceTransport(com.tibco.xpd.xpdl2.Activity)", //$NON-NLS-1$ 
            "public static java.lang.String getProcessPackageVersionNumber(com.tibco.xpd.xpdl2.Package)", //$NON-NLS-1$ 
            "public static com.tibco.xpd.xpdl2.Participant getProcessApiActivityParticipant(com.tibco.xpd.xpdl2.Process)", //$NON-NLS-1$ 
            "protected void finalize() throws java.lang.Throwable", //$NON-NLS-1$ 
            "public final void wait() throws java.lang.InterruptedException", //$NON-NLS-1$ 
            "public final void wait(long,int) throws java.lang.InterruptedException", //$NON-NLS-1$ 
            "public final native void wait(long) throws java.lang.InterruptedException", //$NON-NLS-1$ 
            "public native int hashCode()", //$NON-NLS-1$ 
            "public final native java.lang.Class<?> getClass()", //$NON-NLS-1$ 
            "protected native java.lang.Object clone() throws java.lang.CloneNotSupportedException", //$NON-NLS-1$ 
            "public boolean equals(java.lang.Object)", //$NON-NLS-1$ 
            "public java.lang.String toString()", //$NON-NLS-1$ 
            "public final native void notify()", //$NON-NLS-1$ 
            "public final native void notifyAll()", //$NON-NLS-1$
                };
        checkApiMethods(clazz, methodControlSample);

        String[] nestedClassControlSample = new String[] {
                };
        checkApiNestedClasses(clazz, nestedClassControlSample);

        if (isStrict) {
            checkUntestedApi(clazz);
        }

    }
    

    
}

