/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.analyst.qa.test;

import com.tibco.xpd.core.test.validations.AbstractBaseValidationTest;
import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;

/**
 * ProcessStartInvalidRuleTest
 * <p>
 * ProcessStartInvalidRuleTest - Test selected validations are correctly raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 *
 * Negative test; Dont want to see the problem marker for a catch link intermediate event.
 *
 * @author
 * @since
 */
public class ProcessStartInvalidRuleTest extends AbstractBaseValidationTest {

	public ProcessStartInvalidRuleTest() {
		super(false);
	}

	/**
     * ProcessStartInvalidRuleTest
     * 
     * @throws Exception
     */
    public void testProcessStartInvalidRuleTest() throws Exception {
		doTestValidations();        
        return;
	}

	@Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos = new ValidationsTestProblemMarkerInfo[] { 
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/Dev1/Process Packages/TT1Pkg.xpdl", //$NON-NLS-1$ 
			    		"bpmn.processMustStartWith", //$NON-NLS-1$ 
			    		"_NMT7gH4SEd-6e5hA2q26Og", //$NON-NLS-1$ 
			    		"BPMN : Process can only start with a Start Event, Task or Exclusive Event-Based Gateway. (TT1PkgProcess:CatchLinkEvent)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			                
        };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "ProcessStartInvalidRuleTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.analyst.qa.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources = new TestResourceInfo[] {
            new TestResourceInfo("resources/ProcessStartInvalidRuleTest", "Dev1/Process Packages{processes}/TT1Pkg.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
        };
    
        return testResources;
    }

}
