/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.n2.test.validations;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;

/**
 * ParallelInvocationInDeterminateRuleTest
 * <p>
 * ParallelInvocationInDeterminateRuleTest - Test selected validations are
 * correctly raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 * 
 * 
 * 
 * @author
 * @since
 */
public class N2_15_ParallelInvocationInDeterminateRuleTest extends
        AbstractN2BaseValidationTest {

    public N2_15_ParallelInvocationInDeterminateRuleTest() {
        super(true);
    }

    /**
     * ParallelInvocationInDeterminateRuleTest
     * 
     * @throws Exception
     */
    public void testParallelInvocationInDeterminateRuleTest() throws Exception {
        doTestValidations();
        return;
    }

    @Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos =
                new ValidationsTestProblemMarkerInfo[] {

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_39q8oEGOEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that ReceiveTask is not in progress at the same time as  ReceiveTask2  (ParallelRcvWarningProcess:ReceiveTask)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_39q8oEGOEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that ReceiveTask is not in progress at the same time as  StartMessageEvent  (ParallelRcvWarningProcess:ReceiveTask)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_iAVioEGOEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that StartMessageEvent is not in progress at the same time as  ReceiveTask2  (ParallelRcvWarningProcess:StartMessageEvent)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_iAVioEGOEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that StartMessageEvent is not in progress at the same time as  ReceiveTask  (ParallelRcvWarningProcess:StartMessageEvent)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_1nw1MEGOEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that CoAssociated1 is not in progress at the same time as  CoASsociated2  (ParallelRcvWarningProcess:CoAssociated1)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_4a4dEEGOEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that ReceiveTask2 is not in progress at the same time as  ReceiveTask  (ParallelRcvWarningProcess:ReceiveTask2)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_4a4dEEGOEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that ReceiveTask2 is not in progress at the same time as  StartMessageEvent  (ParallelRcvWarningProcess:ReceiveTask2)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/MIRcvTask/Process Packages/ParallelRcvWarning.xpdl", //$NON-NLS-1$ 
                                "bx.rcvtaskeventscorrelation.behaviourindeterminate", //$NON-NLS-1$ 
                                "_LIWBwEGPEd-tBqXcwlLWgg", //$NON-NLS-1$ 
                                "Process Manager 1.x : Ensure that CoASsociated2 is not in progress at the same time as  CoAssociated1  (ParallelRcvWarningProcess:CoASsociated2)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "ParallelInvocationInDeterminateRuleTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.n2.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources =
                new TestResourceInfo[] {
                        new TestResourceInfo(
                                "resources/ParallelInvocationInDeterminateRuleTest", "MIRcvTask/Process Packages{processes}/ParallelRcvWarning.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
                        new TestResourceInfo(
                                "resources/ParallelInvocationInDeterminateRuleTest", "MIRcvTask/Service Descriptors{wsdl}/Sample.wsdl"), //$NON-NLS-1$ //$NON-NLS-2$
                };

        return testResources;
    }

}
