<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://www.tibco.com/bs3.0/_jtYGYIauEeS4I9GGrysJHA_myWsdl__5khY0IauEeS4I9GGrysJHA" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="N2_39_CorrelateImmediatelyFeatureValidationTest" targetNamespace="http://www.tibco.com/bs3.0/_jtYGYIauEeS4I9GGrysJHA_myWsdl__5khY0IauEeS4I9GGrysJHA" tibex:ServiceTask="_5khY0IauEeS4I9GGrysJHA" tibex:XPDL="N2_39_CorrelateImmediatelyFeatureValidationTest.xpdl" tibex:process="_jtYGYYauEeS4I9GGrysJHA">
  <wsdl:types>
    <xsd:schema xmlns="http://www.tibco.com/bs3.0/_jtYGYIauEeS4I9GGrysJHA_myWsdl__5khY0IauEeS4I9GGrysJHA" targetNamespace="http://www.tibco.com/bs3.0/_jtYGYIauEeS4I9GGrysJHA_myWsdl__5khY0IauEeS4I9GGrysJHA"/>
  </wsdl:types>
  <wsdl:message name="N2_39_CorrelateImmediatelyFeatureValidationTestProcess_myWsdl_INPUT"/>
  <wsdl:message name="N2_39_CorrelateImmediatelyFeatureValidationTestProcess_myWsdl_OUTPUT"/>
  <wsdl:portType name="N2_39_CorrelateImmediatelyFeatureValidationTestProcess" tibex:FlowContainer="_jtYGYYauEeS4I9GGrysJHA">
    <wsdl:documentation>
      <DocumentationElement Documentation=""/>
    </wsdl:documentation>
    <wsdl:operation name="myWsdl">
      <wsdl:input message="ns:N2_39_CorrelateImmediatelyFeatureValidationTestProcess_myWsdl_INPUT" tibex:Event="_5khY0IauEeS4I9GGrysJHA"/>
      <wsdl:output message="ns:N2_39_CorrelateImmediatelyFeatureValidationTestProcess_myWsdl_OUTPUT"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
