<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://www.tibco.com/bs3.0/_1ohDkEhnEd-HtfX1khV6Wg" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ValidateGeneratedWsdlIsDerivedTest" targetNamespace="http://www.tibco.com/bs3.0/_1ohDkEhnEd-HtfX1khV6Wg" tibex:XPDL="ValidateGeneratedWsdlIsDerivedTest.xpdl">
  <wsdl:types>
    <xsd:schema xmlns="http://www.tibco.com/bs3.0/_1ohDkEhnEd-HtfX1khV6Wg" targetNamespace="http://www.tibco.com/bs3.0/_1ohDkEhnEd-HtfX1khV6Wg">
      <xsd:simpleType name="string_50">
        <xsd:restriction base="xsd:string">
          <xsd:maxLength value="50"/>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ValidateGeneratedWsdlIsDerivedTestProcess_StartEvent_INPUT">
    <wsdl:part name="Parameter" type="ns:string_50"/>
    <wsdl:part name="Parameter2" type="ns:string_50"/>
  </wsdl:message>
  <wsdl:message name="ValidateGeneratedWsdlIsDerivedTestProcess_StartEvent_OUTPUT">
    <wsdl:part name="Parameter" type="ns:string_50"/>
    <wsdl:part name="Parameter2" type="ns:string_50"/>
  </wsdl:message>
  <wsdl:portType name="ValidateGeneratedWsdlIsDerivedTestProcess" tibex:FlowContainer="_1p3HYEhnEd-HtfX1khV6Wg">
    <wsdl:operation name="StartEvent">
      <wsdl:input message="ns:ValidateGeneratedWsdlIsDerivedTestProcess_StartEvent_INPUT" tibex:Event="_EEtAUkhoEd-HtfX1khV6Wg"/>
      <wsdl:output message="ns:ValidateGeneratedWsdlIsDerivedTestProcess_StartEvent_OUTPUT" tibex:Event="_EEtAUkhoEd-HtfX1khV6Wg"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
