/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.implementer.nativeservices.emailservice.email.provider;

import com.tibco.xpd.implementer.nativeservices.emailservice.email.util.EmailAdapterFactory;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class EmailItemProviderAdapterFactory extends EmailAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public static final String copyright = "Copyright (c) TIBCO Software Inc 2004, 2006. All rights reserved."; //$NON-NLS-1$

	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection supportedTypes = new ArrayList();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public EmailItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.AttachmentType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected AttachmentTypeItemProvider attachmentTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.AttachmentType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createAttachmentTypeAdapter() {
		if (attachmentTypeItemProvider == null) {
			attachmentTypeItemProvider = new AttachmentTypeItemProvider(this);
		}

		return attachmentTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.DefinitionType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DefinitionTypeItemProvider definitionTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.DefinitionType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDefinitionTypeAdapter() {
		if (definitionTypeItemProvider == null) {
			definitionTypeItemProvider = new DefinitionTypeItemProvider(this);
		}

		return definitionTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.DocumentRoot} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DocumentRootItemProvider documentRootItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.DocumentRoot}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createDocumentRootAdapter() {
		if (documentRootItemProvider == null) {
			documentRootItemProvider = new DocumentRootItemProvider(this);
		}

		return documentRootItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.EmailType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected EmailTypeItemProvider emailTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.EmailType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createEmailTypeAdapter() {
		if (emailTypeItemProvider == null) {
			emailTypeItemProvider = new EmailTypeItemProvider(this);
		}

		return emailTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.ErrorType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ErrorTypeItemProvider errorTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.ErrorType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createErrorTypeAdapter() {
		if (errorTypeItemProvider == null) {
			errorTypeItemProvider = new ErrorTypeItemProvider(this);
		}

		return errorTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.FilesType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FilesTypeItemProvider filesTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.FilesType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFilesTypeAdapter() {
		if (filesTypeItemProvider == null) {
			filesTypeItemProvider = new FilesTypeItemProvider(this);
		}

		return filesTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.FromType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected FromTypeItemProvider fromTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.FromType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createFromTypeAdapter() {
		if (fromTypeItemProvider == null) {
			fromTypeItemProvider = new FromTypeItemProvider(this);
		}

		return fromTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.SMTPType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected SMTPTypeItemProvider smtpTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.SMTPType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createSMTPTypeAdapter() {
		if (smtpTypeItemProvider == null) {
			smtpTypeItemProvider = new SMTPTypeItemProvider(this);
		}

		return smtpTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.TextMappingType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected TextMappingTypeItemProvider textMappingTypeItemProvider;

	/**
	 * This creates an adapter for a {@link com.tibco.xpd.implementer.nativeservices.emailservice.email.TextMappingType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter createTextMappingTypeAdapter() {
		if (textMappingTypeItemProvider == null) {
			textMappingTypeItemProvider = new TextMappingTypeItemProvider(this);
		}

		return textMappingTypeItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory
				.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void setParentAdapterFactory(
			ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class)
					|| (((Class) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public void dispose() {
		if (attachmentTypeItemProvider != null)
			attachmentTypeItemProvider.dispose();
		if (definitionTypeItemProvider != null)
			definitionTypeItemProvider.dispose();
		if (documentRootItemProvider != null)
			documentRootItemProvider.dispose();
		if (emailTypeItemProvider != null)
			emailTypeItemProvider.dispose();
		if (errorTypeItemProvider != null)
			errorTypeItemProvider.dispose();
		if (filesTypeItemProvider != null)
			filesTypeItemProvider.dispose();
		if (fromTypeItemProvider != null)
			fromTypeItemProvider.dispose();
		if (smtpTypeItemProvider != null)
			smtpTypeItemProvider.dispose();
		if (textMappingTypeItemProvider != null)
			textMappingTypeItemProvider.dispose();
	}

}
