<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="deploy"
    nsURI="http:///com/tibco/xpd/deploy/model.ecore" nsPrefix="com.tibco.xpd.deploy.model">
  <eClassifiers xsi:type="ecore:EClass" name="ServerConfig" eSuperTypes="#//NamedElement">
    <eOperations name="getConfigParameter" eType="#//ConfigParameter">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configParameters" upperBound="-1"
        eType="#//ConfigParameter" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="" unsettable="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configParameterInfo" eType="#//ConfigParameterInfo"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerType" eSuperTypes="#//NamedElement #//Loadable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverConfigInfo" eType="#//ServerConfigInfo"
        transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connectionFactory" eType="#//EConnectionFactory"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeType" eType="#//RuntimeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="supportedRepositoryTypes"
        upperBound="-1" eType="#//RepositoryType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="suppressConectivity" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerConfigInfo" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="configParameterInfos" ordered="false"
        upperBound="-1" eType="#//ConfigParameterInfo" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigParameterInfo" eSuperTypes="#//NamedElement">
    <eOperations name="getFacet" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getFacetsMap">
      <eGenericType eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EMap">
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
        <eTypeArguments eClassifier="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      </eGenericType>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="icon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="parameterType" eType="#//ConfigParameterType"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="required" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="automatic" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="facets" upperBound="-1"
        eType="#//ParameterFacet" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ServerState">
    <eLiterals name="DISCONNECTED" literal="Disconnected"/>
    <eLiterals name="CONNECTED" value="1" literal="Connected"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Module" abstract="true" interface="true"
      eSuperTypes="#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerModule" eSuperTypes="#//Module #//LeafElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Server" eSuperTypes="#//UniqueIdElement #//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverType" eType="#//ServerType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverConfig" eType="#//ServerConfig"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="serverState" eType="#//ServerState"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="connection" eType="#//EConnection"
        transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repository" eType="#//Repository"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtime" eType="#//Runtime"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverElements" upperBound="-1"
        eType="#//ServerElement" transient="true" derived="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workspaceModules" upperBound="-1"
        eType="#//WorkspaceModule" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverGroup" eType="#//ServerGroup"
        eOpposite="#//ServerGroup/members"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerElement" abstract="true" interface="true"
      eSuperTypes="#//NamedElement">
    <eOperations name="getConfigParameter" eType="#//ConfigParameter">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverElementType" eType="#//ServerElementType"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverElementState" eType="#//ServerElementState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//ConfigParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerContainer">
    <eOperations name="getRepositoryTypeById" eType="#//RepositoryType">
      <eParameters name="repositoryTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getServerTypeById" eType="#//ServerType">
      <eParameters name="serverTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getRuntimeTypeById" eType="#//RuntimeType">
      <eParameters name="runtimeTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDefaultNewRuntimeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getDefaultNewServerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eParameters name="prefix" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="isValidNewRuntimeName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="isValidNewServerName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getServerGroupTypeById" eType="#//ServerGroupType">
      <eParameters name="serverGroupTypeId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="servers" upperBound="-1"
        eType="#//Server" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimes" upperBound="-1"
        eType="#//Runtime" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverTypes" upperBound="-1"
        eType="#//ServerType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryTypes" upperBound="-1"
        eType="#//RepositoryType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeTypes" upperBound="-1"
        eType="#//RuntimeType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverGroupTypes" upperBound="-1"
        eType="#//ServerGroupType" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverGroups" upperBound="-1"
        eType="#//ServerGroup" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EConnection" instanceClassName="com.tibco.xpd.deploy.model.extension.Connection"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EDataType" name="EConnectionFactory" instanceClassName="com.tibco.xpd.deploy.model.extension.ConnectionFactory"
      serializable="false"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ConfigParameterType">
    <eLiterals name="STRING" literal="string"/>
    <eLiterals name="BOOLEAN" value="1" literal="boolean"/>
    <eLiterals name="INTEGER" value="2" literal="integer"/>
    <eLiterals name="PASSWORD" value="3" literal="password"/>
    <eLiterals name="FILE" value="4" literal="file"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryType" eSuperTypes="#//NamedElement #//Loadable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryParameterInfos"
        upperBound="-1" eType="#//ConfigParameterInfo" transient="true" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="repositoryPublisher" eType="#//ERepositoryPublisher"
        transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DeploymentType">
    <eLiterals name="ON_REQUEST" literal="On Request"/>
    <eLiterals name="AUTOMATICALLY" value="1" literal="Automatically"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Repository">
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryType" eType="#//RepositoryType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="repositoryConfig" eType="#//RepositoryConfig"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="ERepositoryPublisher" instanceClassName="com.tibco.xpd.deploy.model.extension.RepositoryPublisher"/>
  <eClassifiers xsi:type="ecore:EClass" name="RepositoryConfig">
    <eAnnotations/>
    <eOperations name="getConfigParameter" eType="#//ConfigParameter">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configParameters" upperBound="-1"
        eType="#//ConfigParameter" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Runtime" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeType" eType="#//RuntimeType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeConfig" eType="#//RuntimeConfig"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeType" eSuperTypes="#//NamedElement #//Loadable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="runtimeParameterInfos"
        upperBound="-1" eType="#//ConfigParameterInfo" transient="true" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RuntimeConfig">
    <eOperations name="getConfigParameter" eType="#//ConfigParameter">
      <eParameters name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="configParameters" upperBound="-1"
        eType="#//ConfigParameter" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContainerElement" abstract="true" interface="true"
      eSuperTypes="#//ServerElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//ServerElement" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LeafElement" abstract="true" interface="true"
      eSuperTypes="#//ServerElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ModuleContainer" eSuperTypes="#//ContainerElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ServerElementType">
    <eStructuralFeatures xsi:type="ecore:EReference" name="operations" upperBound="-1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" upperBound="-1"
        eType="#//ServerElementState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="#//NamedElement">
    <eOperations name="canExecute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="serverElement" eType="#//ServerElement"/>
    </eOperations>
    <eOperations name="execute" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EJavaObject"
        eExceptions="#//EDeploymentException">
      <eParameters name="serverElement" eType="#//ServerElement"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="toState" eType="#//ServerElementState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerElementState" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="possibleOperations" upperBound="-1"
        eType="#//Operation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceModule" eSuperTypes="#//Module">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="workspaceSrcPath" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="moduleKind" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dirty" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EDeploymentException" instanceClassName="com.tibco.xpd.deploy.model.extension.DeploymentException"/>
  <eClassifiers xsi:type="ecore:EClass" name="UniqueIdElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" defaultValueLiteral="" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerGroup" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="#//Server" eOpposite="#//Server/serverGroup"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverGroupType" lowerBound="1"
        eType="#//ServerGroupType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ServerGroupType" eSuperTypes="#//NamedElement #//Loadable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="serverTypes" upperBound="-1"
        eType="#//ServerType" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Loadable" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="valid" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        transient="true" defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lastExtensionId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ParameterFacet">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
