<?xml version="1.0" encoding="UTF-8"?>
<!--Created by TIBCO WSDL-->
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://xmlns.example.com/1235476171875" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:ns0="http://www.amsbqa.com/linda24/SchoolWSDL2" name="Untitled" targetNamespace="http://xmlns.example.com/1235476171875">
    <wsdl:import namespace="http://www.amsbqa.com/linda24/SchoolWSDL2" location="SchoolWSDL2.wsdl"/>
    <wsdl:service name="SchoolWSDL2-service0">
        <wsdl:port name="PortTypeEndpoint0" binding="tns:PortTypeEndpoint0Binding">
            <soap:address location="http://jiangjun-lt:8934/WSDL/SchoolWSDL2-service0.serviceagent/PortTypeEndpoint0"/>
        </wsdl:port>
    </wsdl:service>
    <wsdl:binding name="PortTypeEndpoint0Binding" type="ns0:PortType">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="Operation">
            <soap:operation style="document" soapAction="/WSDL/SchoolWSDL2-service0.serviceagent/PortTypeEndpoint0/Operation"/>
            <wsdl:input>
                <soap:body use="literal" parts="part1"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="part1"/>
            </wsdl:output>
        </wsdl:operation>
        <wsdl:operation name="Operation1">
            <soap:operation style="document" soapAction="/WSDL/SchoolWSDL2-service0.serviceagent/PortTypeEndpoint0/Operation1"/>
            <wsdl:input>
                <soap:body use="literal" parts="part1"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" parts="part1"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>