package com.tibco.xpd.core.createtestwizards.generators;

import com.tibco.xpd.core.createtestwizards.generatordata.*;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;

public class ValidationTestJavaClassGenerator
{
  protected static String nl;
  public static synchronized ValidationTestJavaClassGenerator create(String lineSeparator)
  {
    nl = lineSeparator;
    ValidationTestJavaClassGenerator result = new ValidationTestJavaClassGenerator();
    nl = null;
    return result;
  }

  public final String NL = nl == null ? (System.getProperties().getProperty("line.separator")) : nl;
  protected final String TEXT_1 = "/**" + NL + " * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved." + NL + " */";
  protected final String TEXT_2 = NL + "package ";
  protected final String TEXT_3 = ";" + NL + "" + NL + "import ";
  protected final String TEXT_4 = ".";
  protected final String TEXT_5 = ";" + NL + "import com.tibco.xpd.core.test.util.TestResourceInfo;" + NL + "import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;" + NL + "" + NL + "/**" + NL + " * ";
  protected final String TEXT_6 = NL + " * <p>" + NL + " * ";
  protected final String TEXT_7 = " - Test selected validations are correctly raised." + NL + " * </p>" + NL + " * <p>" + NL + " * Generated by: createBaseTest.javajet" + NL + " * </p>" + NL + " *" + NL + " * ";
  protected final String TEXT_8 = NL + " *" + NL + " * @author" + NL + " * @since" + NL + " */" + NL + "public class ";
  protected final String TEXT_9 = " extends ";
  protected final String TEXT_10 = " {" + NL + "" + NL + "\tpublic ";
  protected final String TEXT_11 = "() {" + NL + "\t\tsuper(";
  protected final String TEXT_12 = ");" + NL + "\t}" + NL + "" + NL + "\t/**" + NL + "     * ";
  protected final String TEXT_13 = NL + "     * " + NL + "     * @throws Exception" + NL + "     */" + NL + "    public void test";
  protected final String TEXT_14 = "() throws Exception {" + NL + "\t\tdoTestValidations();        " + NL + "        return;" + NL + "\t}" + NL + "" + NL + "\t@Override" + NL + "    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {" + NL + "        ValidationsTestProblemMarkerInfo[] markerInfos = new ValidationsTestProblemMarkerInfo[] { " + NL + "\t\t\t";
  protected final String TEXT_15 = NL + "\t\t\t    new ValidationsTestProblemMarkerInfo(" + NL + "\t\t\t    \t\t\"";
  protected final String TEXT_16 = "\", //$NON-NLS-1$ " + NL + "\t\t\t    \t\t\"";
  protected final String TEXT_17 = "\"), //$NON-NLS-1$ " + NL + "\t\t\t    \t\t" + NL + "\t\t\t";
  protected final String TEXT_18 = "                " + NL + "        };" + NL + "        return markerInfos;" + NL + "    }" + NL + "" + NL + "    @Override" + NL + "    protected String getTestName() {" + NL + "        return \"";
  protected final String TEXT_19 = "\"; //$NON-NLS-1$" + NL + "    }" + NL + "" + NL + "    @Override" + NL + "    protected String getTestPlugInId() {" + NL + "        return \"";
  protected final String TEXT_20 = "\"; //$NON-NLS-1$" + NL + "    }" + NL + "" + NL + "    @Override" + NL + "    protected TestResourceInfo[] getTestResources() {" + NL + "        TestResourceInfo[] testResources = new TestResourceInfo[] {";
  protected final String TEXT_21 = NL + "            new TestResourceInfo(\"";
  protected final String TEXT_22 = "\", \"";
  protected final String TEXT_23 = "\"), //$NON-NLS-1$ //$NON-NLS-2$";
  protected final String TEXT_24 = NL + "        };" + NL + "    " + NL + "        return testResources;" + NL + "    }" + NL + "" + NL + "}";
  protected final String TEXT_25 = NL;

  public String generate(Object argument)
  {
    final StringBuffer stringBuffer = new StringBuffer();
    stringBuffer.append(TEXT_1);
     ValidationTestJavaClassGeneratorData data = (ValidationTestJavaClassGeneratorData)argument; 
    stringBuffer.append(TEXT_2);
    stringBuffer.append(data.testPackageId);
    stringBuffer.append(TEXT_3);
    stringBuffer.append(data.testSuperClassPackage);
    stringBuffer.append(TEXT_4);
    stringBuffer.append(data.testSuperClassName);
    stringBuffer.append(TEXT_5);
    stringBuffer.append(data.testClassName);
    stringBuffer.append(TEXT_6);
    stringBuffer.append(data.testName);
    stringBuffer.append(TEXT_7);
    stringBuffer.append(data.testDescription);
    stringBuffer.append(TEXT_8);
    stringBuffer.append(data.testClassName);
    stringBuffer.append(TEXT_9);
    stringBuffer.append(data.testSuperClassName);
    stringBuffer.append(TEXT_10);
    stringBuffer.append(data.testClassName);
    stringBuffer.append(TEXT_11);
    stringBuffer.append(data.isCheckProblemsExists);
    stringBuffer.append(TEXT_12);
    stringBuffer.append(data.testName);
    stringBuffer.append(TEXT_13);
    stringBuffer.append(data.testMethodName);
    stringBuffer.append(TEXT_14);
     for (ValidationsTestProblemMarkerInfo markerInfo : data.markerInfos) { 
    stringBuffer.append(TEXT_15);
    stringBuffer.append(markerInfo.getResourceURI());
    stringBuffer.append(TEXT_16);
    stringBuffer.append(markerInfo.getProblemId());
    stringBuffer.append(TEXT_16);
    stringBuffer.append(markerInfo.getLocationURI());
    stringBuffer.append(TEXT_16);
    stringBuffer.append(markerInfo.getProblemText());
    stringBuffer.append(TEXT_16);
    stringBuffer.append(markerInfo.getQuickFixLabel());
    stringBuffer.append(TEXT_17);
     } 
    stringBuffer.append(TEXT_18);
    stringBuffer.append(data.testName);
    stringBuffer.append(TEXT_19);
    stringBuffer.append(data.testPluginId);
    stringBuffer.append(TEXT_20);
     for (String testResourcePath : data.testResourcePaths) { 
    stringBuffer.append(TEXT_21);
    stringBuffer.append(data.baseResourcePath);
    stringBuffer.append(TEXT_22);
    stringBuffer.append(testResourcePath);
    stringBuffer.append(TEXT_23);
     } 
    stringBuffer.append(TEXT_24);
    stringBuffer.append(TEXT_25);
    return stringBuffer.toString();
  }
}
