/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.HomeClass;
import com.tibco.xpd.xpdl2.JndiName;
import com.tibco.xpd.xpdl2.Method;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.EjbApplication}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface EjbApplicationValidator {
    boolean validate();

    boolean validateJndiName(JndiName value);

    boolean validateHomeClass(HomeClass value);

    boolean validateMethod(Method value);
}
