/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.JoinSplitType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Route}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface RouteValidator {
    boolean validate();

    boolean validateGatewayType(JoinSplitType value);

    boolean validateInstantiate(boolean value);

    boolean validateMarkerVisible(boolean value);

    boolean validateIncomingCondition(String value);

    boolean validateOutgoingCondition(String value);
}
