/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdl2.validation;

import com.tibco.xpd.xpdl2.TaskApplication;
import com.tibco.xpd.xpdl2.TaskManual;
import com.tibco.xpd.xpdl2.TaskReceive;
import com.tibco.xpd.xpdl2.TaskReference;
import com.tibco.xpd.xpdl2.TaskScript;
import com.tibco.xpd.xpdl2.TaskSend;
import com.tibco.xpd.xpdl2.TaskService;
import com.tibco.xpd.xpdl2.TaskUser;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdl2.Task}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TaskValidator {
    boolean validate();

    boolean validateTaskService(TaskService value);

    boolean validateTaskReceive(TaskReceive value);

    boolean validateTaskManual(TaskManual value);

    boolean validateTaskReference(TaskReference value);

    boolean validateTaskScript(TaskScript value);

    boolean validateTaskSend(TaskSend value);

    boolean validateTaskUser(TaskUser value);

    boolean validateTaskApplication(TaskApplication value);
}
