<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://www.books.org" xmlns:ns2="http://www.xyzcorp/procureservice/UserProfile" xmlns:tns="http://www.amsbqa.com/linda25/WSDL1importWSDL2/WSDL2importScheam1/WSDL2ImportSchema2/WSDL2" targetNamespace="http://www.amsbqa.com/linda25/WSDL1importWSDL2/WSDL2importScheam1/WSDL2ImportSchema2/WSDL2">
    <import namespace="http://www.xyzcorp/procureservice/UserProfile" location="Schema/HotelUserProfile.xsd"/>
    <import namespace="http://www.books.org" location="Schema/SchemaName.xsd"/>
    <message name="Message">
        <part name="part1" element="ns:BookStore"/>
    </message>
    <message name="Message1">
        <part name="part1" type="ns2:HotelPreference"/>
    </message>
    <message name="Message2">
        <part name="part1" element="ns:Publisher"/>
    </message>
    <message name="Message3">
        <part name="part1" element="ns:Author"/>
    </message>
</definitions>