/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.validation.wm.test;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.CoreException;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.resources.util.ProjectUtil;

/**
 * XPD2493UserDefPrimitveCoverageTest
 * <p>
 * XPD2493UserDefPrimitveCoverageTest - Test selected validations are correctly
 * raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 * 
 * XPD2493UserDefPrimitveCoverageTest
 * 
 * @author
 * @since
 */
public class XPD2493UserDefPrimitveCoverageTest extends
        AbstractJavaScriptValidatorTest {

    public XPD2493UserDefPrimitveCoverageTest() {
        super(true);
    }

    /**
     * XPD2493UserDefPrimitveCoverageTest
     * 
     * @throws Exception
     */
    public void testXPD2493UserDefPrimitveCoverageTest() throws Exception {
        doTestValidations();
        return;
    }

    /**
     * @see com.tibco.xpd.validation.wm.test.AbstractJavaScriptValidatorTest#configureProject(org.eclipse.core.resources.IProject)
     * 
     * @param project
     */
    @Override
    protected void configureProject(IProject project) {
        super.configureProject(project);
        try {
            ProjectUtil.addNature(project,
                    "com.tibco.xpd.bom.xsdtransform.xsdNature"); //$NON-NLS-1$

            ProjectUtil.addNature(project,
                    "com.tibco.xpd.wsdlgen.wsdlGenNature"); //$NON-NLS-1$

            ProjectUtil.addNature(project,
                    "com.tibco.xpd.wsdltobom.wsdlBomNature"); //$NON-NLS-1$
        } catch (CoreException e) {
            e.printStackTrace();
        }
    }

    @Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos =
                new ValidationsTestProblemMarkerInfo[] {

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:10 column:53, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:101 column:61, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:102 column:61, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:11 column:52, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:114 column:39, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:115 column:38, Method add is not applicable for the provided argument types (Integer) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:116 column:60, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:117 column:60, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:118 column:55, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:119 column:57, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:120 column:56, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:122 column:62, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:123 column:62, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:126 column:33, Method add is not applicable for the provided argument types (Integer) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:127 column:55, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:128 column:55, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:129 column:50, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:13 column:60, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:131 column:57, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:132 column:57, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:14 column:61, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:15 column:58, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:16 column:62, Method addAll is not applicable for the provided argument types (DateTime) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:17 column:70, Method addAll is not applicable for the provided argument types (DateTime) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:2 column:35, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:20 column:35, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:21 column:34, Method add is not applicable for the provided argument types (Integer) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:22 column:35, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:23 column:56, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:24 column:60, Method add is not applicable for the provided argument types (Datetime) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:25 column:62, Method add is not applicable for the provided argument types (Datetimetz) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:26 column:53, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:27 column:51, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:28 column:53, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:29 column:52, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:3 column:34, Method add is not applicable for the provided argument types (Integer) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:31 column:60, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:32 column:61, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:33 column:58, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:34 column:62, Method addAll is not applicable for the provided argument types (DateTime) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:35 column:70, Method addAll is not applicable for the provided argument types (DateTime) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:38 column:39, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:39 column:38, Method add is not applicable for the provided argument types (Integer) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:4 column:35, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:40 column:39, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:41 column:60, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:42 column:60, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:43 column:57, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:44 column:55, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:45 column:57, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:46 column:56, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:48 column:64, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:49 column:65, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:5 column:56, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:50 column:62, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:51 column:62, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:54 column:47, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:55 column:46, Method add is not applicable for the provided argument types (Integer) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:56 column:47, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:57 column:68, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:58 column:68, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:59 column:65, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:6 column:60, Method add is not applicable for the provided argument types (Datetime) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:60 column:63, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:61 column:65, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:62 column:64, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:64 column:72, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:65 column:73, Method addAll is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:66 column:70, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:67 column:70, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:7 column:62, Method add is not applicable for the provided argument types (Datetimetz) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:71 column:38, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:72 column:37, Method add is not applicable for the provided argument types (Integer) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:73 column:59, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:74 column:59, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:75 column:54, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:76 column:56, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:77 column:55, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:79 column:61, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:8 column:53, Method add is not applicable for the provided argument types (Boolean) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:80 column:61, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:83 column:38, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:84 column:59, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:85 column:59, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:86 column:54, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:87 column:56, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:88 column:55, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:9 column:51, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:90 column:61, Method addAll is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:91 column:61, Method addAll is not applicable for the provided argument types (Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:94 column:38, Method add is not applicable for the provided argument types (String) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:95 column:59, Method add is not applicable for the provided argument types (Time) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:96 column:59, Method add is not applicable for the provided argument types (bom.Date) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:97 column:54, Method add is not applicable for the provided argument types (ID) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:98 column:56, Method add is not applicable for the provided argument types (Text) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/XPD2493UserDefPrimitiveCoverage/Process Packages/XPD2493UserDefPrimitiveCoverage.xpdl", //$NON-NLS-1$ 
                                "bx.validateScriptTask", //$NON-NLS-1$ 
                                "_kwbu8AboEeG-V5hrhRaZKg", //$NON-NLS-1$ 
                                "Process Manager 1.x : At Line:99 column:55, Method add is not applicable for the provided argument types (URI) (XPD2493UserDefPrimitiveCoverageProcess:InvalidScript)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "XPD2493UserDefPrimitveCoverageTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.validation.wm.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources =
                new TestResourceInfo[] {
                        new TestResourceInfo(
                                "resources/XPD2493UserDefPrimitveCoverage", "XPD2493UserDefPrimitiveCoverage/Business Objects{bom}/XPD2493UserDefPrimitiveCoverage.bom"), //$NON-NLS-1$ //$NON-NLS-2$
                        new TestResourceInfo(
                                "resources/XPD2493UserDefPrimitveCoverage", "XPD2493UserDefPrimitiveCoverage/Service Descriptors{wsdl}/TextTLE.wsdl"), //$NON-NLS-1$ //$NON-NLS-2$
                        new TestResourceInfo(
                                "resources/XPD2493UserDefPrimitveCoverage", "XPD2493UserDefPrimitiveCoverage/Process Packages{processes}/XPD2493UserDefPrimitiveCoverage.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
                };

        return testResources;
    }

}
