/*
 * Copyright (c) TIBCO Software Inc 2004, 2014. All rights reserved.
 */

package com.tibco.xpd.sce.tests.rasc.contributors;

import static org.junit.Assert.assertArrayEquals;

import java.io.ByteArrayOutputStream;
import java.util.Collection;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;
import org.eclipse.core.runtime.CoreException;

import com.tibco.bpm.dt.rasc.MicroService;
import com.tibco.bpm.dt.rasc.Version;
import com.tibco.bpm.dt.rasc.VersionRange;
import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.util.TestUtil;
import com.tibco.xpd.n2.pe.transform.PERascContributor;
import com.tibco.xpd.n2.test.core.AbstractN2BaseResourceTest;
import com.tibco.xpd.rasc.core.RascAppSummary;
import com.tibco.xpd.rasc.core.RascContext;
import com.tibco.xpd.rasc.core.RascContributor;
import com.tibco.xpd.resources.util.ProjectImporter;
import com.tibco.xpd.resources.util.ProjectUtil2;
import com.tibco.xpd.sce.tests.rasc.contributors.MockRascWriter.WriterContent;

/**
 * Test Process Engine and Page-Flow RASC Contribution.
 *
 * @author pwatson
 * @since 20 Mar 2019
 */
@SuppressWarnings("nls")
public class PERascContributorTest extends AbstractN2BaseResourceTest {

    private ProjectImporter projectImporter;

    /**
     * @see com.tibco.xpd.core.test.util.AbstractBaseResourceTest#getTestName()
     */
    @Override
    protected String getTestName() {
        return "BPEL RASC Transform Test";
    }

    /**
     * @see com.tibco.xpd.core.test.util.AbstractBaseResourceTest#getTestResources()
     */
    @Override
    protected TestResourceInfo[] getTestResources() {
        return new TestResourceInfo[0];
    }

    /**
     * @see com.tibco.xpd.core.test.util.AbstractBaseResourceTest#getTestPlugInId()
     */
    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.sce.test";
    }


    /**
     * @see com.tibco.xpd.core.test.util.AbstractBuildingBaseResourceTest#setUp()
     *
     * @throws Exception
     */
    @Override
    protected void setUp() throws Exception {
        // Sid - Changed to import whole project, using old method did all sorts
        // that SCE validation didn't like.
        // Not sure how this worked since we added checking for problem markers
        // etc.
        // Maybe it was exporting RASC prior to build and validation complete
        // Also moved hasContributionsFor test into here so we only do setup
        // (import and build) once.
        projectImporter = importMainTestProjects();
    }

    /**
     * @see com.tibco.xpd.core.test.util.AbstractBaseResourceTest#tearDown()
     *
     * @throws Exception
     */
    @Override
    protected void tearDown() throws Exception {
        if (projectImporter != null) {
            projectImporter.performDelete();
        }
    }

    public void testProcess() throws Exception {

        // create a mock writer to capture contributor's output
        MockRascWriter writer = new MockRascWriter();

        // find the project in which the test data resides
        IProject project =
                ResourcesPlugin.getWorkspace().getRoot().getProject("RASC");

        assertFalse("Project RASC should not have error problem markers",
                TestUtil.hasErrorProblemMarker(project, true));

        // call the contributor's process() method
        RascContributor fixture = new PERascContributor();

        assertTrue(fixture.hasContributionsFor(project));

        Version version = new Version(
                "1.0.0." + ProjectUtil2.getAutogeneratedQualifier());

        RascAppSummary appSummary = new RascAppSummary() {
            @Override
            public String getName() {
                return null;
            }

            @Override
            public String getInternalName() {
                return null;
            }

            @Override
            public Version getVersion() {
                return version;
            }

            @Override
            public Collection<RascAppSummary> getReferencedProjects()
                    throws CoreException {
                return Collections.emptyList();
            }

            @Override
            public boolean hasAssetType(String aAssetTypeId) {
                return false;
            }

            @Override
            public VersionRange getDependencyRange() {
                return null;
            }
        };

        RascContext rascContext = new RascContext() {
            @Override
            public Version getVersion() {
                return version;
            }

            @Override
            public RascAppSummary getAppSummary() {
                return appSummary;
            }
        };
        fixture.process(project, rascContext, null, writer);

        // these are the expected artefacts and their destinations
        Map<String, TestArtifactData> expected = new HashMap<>();
        expected.put("processOut/pageflow/TestContributor.xpdl/TestPageFowProcess.bpel",
                new TestArtifactData("Test PageFow Process", "TestPageFowProcess", MicroService.UP));

        expected.put("processOut/process/TestContributor.xpdl/TestBusinessProcess.bpel",
                new TestArtifactData("Test Business Process", "TestBusinessProcess", MicroService.BP));

        expected.put("processOut/process/TestContributor.xpdl/DuplicatenamedBusinessProcess.bpel",
                new TestArtifactData("Duplicate named Business Process", "DuplicatenamedBusinessProcess",
                        MicroService.BP));

        expected.put("processOut/process/TestContributor2.xpdl/DuplicatenamedBusinessProcess.bpel",
                new TestArtifactData("Duplicate named Business Process", "DuplicatenamedBusinessProcess",
                        MicroService.BP));

        expected.put("processOut/pageflow/TestContributor2.xpdl/TestBusinessService.bpel",
                new TestArtifactData("Test Business Service", "TestBusinessService", MicroService.UP));

        // All the different combo's of service process.
        expected.put("processOut/pageflow/TestContributor.xpdl/TestServiceProcess4BPandPF.bpel",
                new TestArtifactData("Test Service Process 4 BP and PF", "TestServiceProcess4BPandPF",
                        MicroService.UP));

        expected.put("processOut/process/TestContributor.xpdl/TestServiceProcess4BPandPF.bpel",
                new TestArtifactData("Test Service Process 4 BP and PF", "TestServiceProcess4BPandPF",
                        MicroService.BP));

        expected.put("processOut/process/TestContributor.xpdl/TestServiceProcess4BP.bpel",
                new TestArtifactData("Test Service Process 4 BP", "TestServiceProcess4BP", MicroService.BP));

        expected.put("processOut/pageflow/TestContributor.xpdl/TestServiceProcess4PF.bpel",
                new TestArtifactData("Test Service Process 4 PF", "TestServiceProcess4PF", MicroService.UP));

        // the process package artifacts
        expected.put("processOut/process/TestContributor.xpdl/package.pkg",
                new TestArtifactData("ProcessPackage", "ProcessPackage", MicroService.BP));

        expected.put("processOut/process/TestContributor2.xpdl/package.pkg",
                new TestArtifactData("ProcessPackage2", "ProcessPackage2", MicroService.BP));

        expected.put("processOut/pageflow/TestContributor.xpdl/package.pkg",
                new TestArtifactData("ProcessPackage", "ProcessPackage", MicroService.UP));

        expected.put("processOut/pageflow/TestContributor2.xpdl/package.pkg",
                new TestArtifactData("ProcessPackage2", "ProcessPackage2", MicroService.UP));

        // artifacts should have been added to the writer
        assertEquals(expected.size(), writer.getArtifacts().size());

        for (WriterContent artifact : writer.getArtifacts()) {
            boolean found = false;
            for (Map.Entry<String, TestArtifactData> entry : expected
                    .entrySet()) {
                if (entry.getKey().equals(artifact.getFullPath())) {
                    assertArrayEquals(entry.getKey(), entry.getValue().services,
                            artifact.getServices());

                    // some data was written to the artifact
                    ByteArrayOutputStream fileContent = artifact.getContent();

                    assertTrue(fileContent.size() > 0);

                    assertEquals(artifact.getArtifactName(),
                            entry.getValue().artifactName);
                    assertEquals(artifact.getInternalName(),
                            entry.getValue().internalName);

                    /*
                     * Check that user task work model version number
                     * replacement has happened.
                     */
                    String contentString = fileContent.toString("UTF-8");

                    if (contentString.contains("UserTaskDataModelType")) {
                        String expectedWorkModelVersionRange =
                                "workModelVersionRange=\"[" + version.toString()
                                        + "," + version.toString() + "]\"";

                        assertTrue("User task version range not set correctly",
                                contentString.contains(
                                        expectedWorkModelVersionRange));
                    }

                    found = true;
                    break;
                }
            }
            assertTrue("Unexpected artifact: " + artifact.getFullPath(), found);
        }

    }

    /**
     * Import all projects from test plugin resources for the main test
     * 
     * @return the project importer
     */
    private ProjectImporter importMainTestProjects() {
        /*
         * Import and mgirate the project
         */

        ProjectImporter projectImporter = TestUtil.importProjectsFromZip("com.tibco.xpd.sce.test", //$NON-NLS-1$
                new String[] { "resources/BpelRascTest/RASC/" }, //$NON-NLS-1$
                new String[] { "RASC" }); //$NON-NLS-1$

        assertTrue("Failed to load projects from resources/BpelRascTest/", //$NON-NLS-1$
                projectImporter != null);

        TestUtil.buildAndWait();

        return projectImporter;
    }

    /**
     * Little class for storing expected test results.
     *
     *
     * @author aallway
     * @since 2 Apr 2019
     */
    private static class TestArtifactData {
        String artifactName;

        String internalName;

        MicroService[] services;

        /**
         * @param artifactName
         * @param internalName
         * @param services
         */
        public TestArtifactData(String artifactName, String internalName,
                MicroService... services) {
            super();
            this.artifactName = artifactName;
            this.internalName = internalName;
            this.services = services;
        }
    }
}
