<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:tns="http://www.example.org/One/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="One" targetNamespace="http://www.example.org/One/" tibex:src="file:/C:/temp/XPD7483/XPD-5167/AccountHist.wsdl">

	<wsdl:types>

		<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:cmd-header="http://www.vietinbank.com/serviceenvelope/commonheader" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.vietinbank.com/serviceenvelope/commonheader" version="1.0">
			
			<complexType name="CommonDetailType">
				<sequence>
					<element ref="cmd-header:BusinessDomain">
					</element>
					<element ref="cmd-header:ServiceVersion">
					</element>
				</sequence>
			</complexType>
			
			<element name="BusinessDomain" type="xsd:string">
			</element>
			
			<element name="ServiceVersion" type="xsd:string">
			</element>
			
			<element name="NewType" type="xsd:string">
			</element>
			
		</schema>

	</wsdl:types>

	<wsdl:portType name="One">
	</wsdl:portType>

	<wsdl:binding name="OneSOAP" type="tns:One">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
	</wsdl:binding>

	<wsdl:service name="One">
		<wsdl:port binding="tns:OneSOAP" name="OneSOAP">
			<soap:address location="http://www.example.org/"/>
		</wsdl:port>
	</wsdl:service>

</wsdl:definitions>
