/*
 * Copyright (c) TIBCO Software Inc 2004, 2019. All rights reserved.
 */

package com.tibco.xpd.n2.brm;

import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Map;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.runtime.IProgressMonitor;
import org.eclipse.core.runtime.SubMonitor;
import org.eclipse.emf.ecore.resource.Resource;

import com.tibco.bpm.dt.rasc.MicroService;
import com.tibco.bpm.dt.rasc.PropertyValue;
import com.tibco.bpm.dt.rasc.Version;
import com.tibco.xpd.n2.brm.internal.Messages;
import com.tibco.xpd.n2.resources.util.N2Utils;
import com.tibco.xpd.rasc.core.RascContext;
import com.tibco.xpd.rasc.core.RascContributor;
import com.tibco.xpd.rasc.core.RascWriter;
import com.tibco.xpd.xpdExtension.EmailResource;
import com.tibco.xpd.xpdExtension.ParticipantSharedResource;
import com.tibco.xpd.xpdExtension.RestServiceResource;

/**
 * The RascContributor implementation to add the exported BRM-Models to the
 * RASC, the work-model and work-type models (wm.xml, wt.xml)
 * 
 * @author aallway
 * @since 12 Apr 2019
 */
public class BrmModelsRascContributor implements RascContributor {
    /**
     * The unique identifier for this RascContribution implementation.
     */
    private static final String ID =
            "com.tibco.xpd.n2.brm.rasc.model.contributor"; //$NON-NLS-1$

    /**
     * The name of the manifest attribute to which the collection of shared
     * resource references will be written.
     */
    public static final String SHARED_RESOURCE_MANIFEST_ATTR =
            "Resource-Dependencies"; //$NON-NLS-1$

    /**
     * The shared-resource manifest attribute property that identifies the type
     * of resource.
     */
    private static final String SHARED_RSRC_TYPE_PROP = "type"; //$NON-NLS-1$

    /**
     * The shared-resource manifest attribute property that describes the
     * resource.
     */
    private static final String SHARED_RSRC_DESC_PROP = "description"; //$NON-NLS-1$

    /**
     * The identifies a REST service shared-resource within the manifest
     * attribute "Resource-Dependencies.
     */
    private static final String REST_SERVICE_SHARED_RSRC_TYPE = "HTTPClient"; //$NON-NLS-1$

    /**
     * The identifies an EMail service shared-resource within the manifest
     * attribute "Resource-Dependencies.
     */
    private static final String EMAIL_SERVICE_SHARED_RSRC_TYPE = "EMail"; //$NON-NLS-1$

    /**
     * The MicroServices to which the artifacts generated by this contributor
     * will be delivered.
     */
    private static final MicroService[] WM_MODEL_DESTINATION_SERVICES =
            { MicroService.WM };

    /**
     * The MicroServices to which the artifacts generated by this contributor
     * will be delivered.
     */
    private static final MicroService[] WT_MODEL_DESTINATION_SERVICES =
            { MicroService.WM, MicroService.WP };

    /**
     * The transformer to generate the RASC BRM models.
     */
    private static final BRMGenerator TRANSFORMER = BRMGenerator.getInstance();

    /**
     * @see com.tibco.xpd.rasc.core.RascContributor#getId()
     */
    @Override
    public String getId() {
        return BrmModelsRascContributor.ID;
    }

    /**
     * @see com.tibco.xpd.rasc.core.RascContributor#hasContributionsFor(org.eclipse.core.resources.IProject)
     */
    @Override
    public boolean hasContributionsFor(IProject aProject) {
        return TRANSFORMER.projectHasRelevantContent(aProject);
    }

    /**
     * @see com.tibco.xpd.rasc.core.RascContributor#process(org.eclipse.core.resources.IProject,
     *      com.tibco.xpd.rasc.core.RascContext,
     *      org.eclipse.core.runtime.IProgressMonitor,
     *      com.tibco.xpd.rasc.core.RascWriter)
     *
     * @param aProject
     * @param aContext
     * @param aProgressMonitor
     * @param aWriter
     * @throws Exception
     */
    @Override
    public void process(IProject aProject, RascContext aContext,
            IProgressMonitor aProgressMonitor, RascWriter aWriter)
            throws Exception {

        SubMonitor monitor = SubMonitor.convert(aProgressMonitor,
                Messages.BrmModelsRascContributor_UserTaskModelExport_status,
                2);
        monitor.subTask(
                Messages.BrmModelsRascContributor_UserTaskModelExport_status);

        try {
            // Generate the BRM relevant models
            Version version = aContext.getVersion();

            Map<String, Resource> brmModels =
                    TRANSFORMER.generateBRMModels(aProject, version.toString());

            // has the job been cancelled by the user
            if (monitor.isCanceled()) {
                return;
            }
            monitor.worked(1);

            if ((brmModels != null) && (!brmModels.isEmpty())) {
                // Output the work-model to the rasc.
                Resource wmResource =
                        brmModels.get(BRMGenerator.WORKMODEL_ARTIFACT_NAME);
                if (wmResource != null) {
                    OutputStream output = aWriter.addContent(
                            BRMGenerator.WORKMODEL_ARTIFACT_NAME,
                            BRMGenerator.WORKMODEL_ARTIFACT_NAME,
                            BRMGenerator.WORKMODEL_ARTIFACT_NAME,
                            BrmModelsRascContributor.WM_MODEL_DESTINATION_SERVICES);

                    // output the rasc model to the rasc artifact
                    wmResource.save(output, N2Utils.getDefaultXMLSaveOptions());
                }

                // Output the work-type model to rasc.
                Resource wtResource =
                        brmModels.get(BRMGenerator.WORKTYPE_ARTIFACT_NAME);
                if (wtResource != null) {
                    MicroService[] targetServices;

                    targetServices = WT_MODEL_DESTINATION_SERVICES;

                    OutputStream output = aWriter.addContent(
                            BRMGenerator.WORKTYPE_ARTIFACT_NAME,
                            BRMGenerator.WORKTYPE_ARTIFACT_NAME,
                            BRMGenerator.WORKTYPE_ARTIFACT_NAME,
                            targetServices);

                    // output the rasc model to the rasc artifact
                    wtResource.save(output, N2Utils.getDefaultXMLSaveOptions());
                }
            }

            // add the shared-resource references to the RASC
            addSharedResources(aWriter,
                    TRANSFORMER.getSharedResources(aProject));
        } finally {
            monitor.worked(1);
            monitor.subTask(""); //$NON-NLS-1$
            monitor.done();
        }
    }

    /**
     * Adds the given collection of shared resource references to the RASC (via
     * the given RascWriter).
     * 
     * @param aWriter
     *            the accessor for the RASC.
     * @param aSharedResources
     *            the collection of shared resource referencs.
     */
    private void addSharedResources(RascWriter aWriter,
            Collection<ParticipantSharedResource> aSharedResources) {
        if (aSharedResources.isEmpty()) {
            return;
        }

        // create a list of RASC manifest PropertyValues for each resource
        ArrayList<PropertyValue> attrValue = new ArrayList<>();
        for (ParticipantSharedResource sharedResource : aSharedResources) {
            RestServiceResource restService = sharedResource.getRestService();
            if (restService != null) {
                PropertyValue property = new PropertyValue();
                property.setValue(restService.getResourceName());
                property.setAttribute(SHARED_RSRC_TYPE_PROP,
                        REST_SERVICE_SHARED_RSRC_TYPE);
                property.setAttribute(SHARED_RSRC_DESC_PROP,
                        restService.getDescription());
                attrValue.add(property);
                continue;
            }

            EmailResource email = sharedResource.getEmail();
            if (email != null) {
                PropertyValue property = new PropertyValue();
                property.setValue(email.getInstanceName());
                property.setAttribute(SHARED_RSRC_TYPE_PROP,
                        EMAIL_SERVICE_SHARED_RSRC_TYPE);
                attrValue.add(property);
                continue;
            }
        }

        if (attrValue.isEmpty()) {
            return;
        }

        // add the references to the RASC manifest
        PropertyValue[] values =
                attrValue.toArray(new PropertyValue[attrValue.size()]);
        aWriter.setManifestAttribute(SHARED_RESOURCE_MANIFEST_ATTR, values);
    }
}
