<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://www.tibco.com/bs3.0/_od3AMGEWEem0lq-eL9iD2A" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="BPMProjectMigration_ProcessValidation" targetNamespace="http://www.tibco.com/bs3.0/_od3AMGEWEem0lq-eL9iD2A" tibex:XPDL="BPMProjectMigration_ProcessValidation.dflow">
  <wsdl:types>
    <xsd:schema xmlns="http://www.tibco.com/bs3.0/_od3AMGEWEem0lq-eL9iD2A" targetNamespace="http://www.tibco.com/bs3.0/_od3AMGEWEem0lq-eL9iD2A"/>
  </wsdl:types>
  <wsdl:message name="BPMProjectMigration_ProcessValidationDecisionFlow_StartBPMProjectMigration_ProcessValidationDecisionFlow_INPUT"/>
  <wsdl:message name="BPMProjectMigration_ProcessValidationDecisionFlow_StartBPMProjectMigration_ProcessValidationDecisionFlow_OUTPUT"/>
  <wsdl:portType name="BPMProjectMigration_ProcessValidationDecisionFlow" tibex:FlowContainer="_od9t4GEWEem0lq-eL9iD2A">
    <wsdl:documentation>
      <DocumentationElement Documentation=""/>
    </wsdl:documentation>
    <wsdl:operation name="StartBPMProjectMigration_ProcessValidationDecisionFlow">
      <wsdl:input message="ns:BPMProjectMigration_ProcessValidationDecisionFlow_StartBPMProjectMigration_ProcessValidationDecisionFlow_INPUT" tibex:Event="_uEXVsGEWEem0lq-eL9iD2A"/>
      <wsdl:output message="ns:BPMProjectMigration_ProcessValidationDecisionFlow_StartBPMProjectMigration_ProcessValidationDecisionFlow_OUTPUT" tibex:Event="_uEXVsGEWEem0lq-eL9iD2A"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
