<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://www.tibco.com/bs3.0/_NlG9gDDYEd-OvJIRy530BQ" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="ProcessPackage" targetNamespace="http://www.tibco.com/bs3.0/_NlG9gDDYEd-OvJIRy530BQ" tibex:XPDL="ProcessPackage.xpdl" tibex:ServiceTask="_bVvfADDcEd-OvJIRy530BQ" tibex:process="_NmAVYDDYEd-OvJIRy530BQ">
  <wsdl:types>
    <xsd:schema xmlns="http://www.tibco.com/bs3.0/_NlG9gDDYEd-OvJIRy530BQ" targetNamespace="http://www.tibco.com/bs3.0/_NlG9gDDYEd-OvJIRy530BQ">
      <xsd:simpleType name="string_50">
        <xsd:restriction base="xsd:string">
          <xsd:maxLength value="50"/>
        </xsd:restriction>
      </xsd:simpleType>
    </xsd:schema>
  </wsdl:types>
  <wsdl:message name="ProcessPackageProcess_ServiceTask_INPUT">
    <wsdl:part name="Parameter" type="ns:string_50"/>
    <wsdl:part name="Parameter2" type="ns:string_50"/>
  </wsdl:message>
  <wsdl:message name="ProcessPackageProcess_ServiceTask_OUTPUT">
    <wsdl:part name="Parameter" type="ns:string_50"/>
    <wsdl:part name="Parameter2" type="ns:string_50"/>
  </wsdl:message>
  <wsdl:portType name="ProcessPackageProcess" tibex:FlowContainer="_NmAVYDDYEd-OvJIRy530BQ">
    <wsdl:operation name="ServiceTask">
      <wsdl:input message="ns:ProcessPackageProcess_ServiceTask_INPUT" tibex:Event="_bVvfADDcEd-OvJIRy530BQ"/>
      <wsdl:output message="ns:ProcessPackageProcess_ServiceTask_OUTPUT" tibex:Event="_bVvfADDcEd-OvJIRy530BQ"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
