/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.sce.tests.validation;

import java.util.List;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.ResourcesPlugin;

import com.tibco.xpd.bom.resources.utils.BOMUtils;
import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;

/**
 * AceBomMigrationValidationsTest
 * <p>
 * AceBomMigrationValidationsTest - Test selected validations are correctly
 * raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 *
 * AceBomMigrationValidationsTest
 *
 * @author
 * @since
 */
public class AceBomMigrationValidationsTest
        extends AbstractN2BaseValidationTest {

    public AceBomMigrationValidationsTest() {
        super(true);
		cleanProjectAtEnd = false;
    }

    /**
     * @see com.tibco.xpd.core.test.util.AbstractBuildingBaseResourceTest#setUpBeforeBuild()
     *
     */
    @Override
    protected void setUpBeforeBuild() {
        super.setUpBeforeBuild();

        /*
         * make sure BOM project is configured as Business Data project to avoid
         * getting unexpected problem markers unrelated to this test.
         */
        BOMUtils.setAsBusinessDataProject(ResourcesPlugin.getWorkspace()
                .getRoot().getProject("BPMProjectMigration_BOMValidations")); //$NON-NLS-1$

    }

    /**
     * AceBomMigrationValidationsTest
     * 
     * @throws Exception
     */
    public void testAceBomMigrationValidationsTest() throws Exception {
        /*
         * Before checking that the expected problems have been raised, make
         * sure that the BOMs that are expected to be ok have no problems.
         */
        IFile okFile1 = getTestFile("SupportedAttribTypes.bom"); //$NON-NLS-1$

        List<ValidationsTestProblemMarkerInfo> problemMarkers =
                getProblemMarkers(okFile1);
        String the1stProblem = null;
        if (problemMarkers.size() > 0) {
            ValidationsTestProblemMarkerInfo markerInfo = problemMarkers.get(0);
            the1stProblem = markerInfo.getProblemId() + "::" //$NON-NLS-1$
                    + markerInfo.getResourceURI() + "." //$NON-NLS-1$
                    + markerInfo.getLocationURI() + ":\n  \"" //$NON-NLS-1$
                    + markerInfo.getProblemText() + "\"\n"; //$NON-NLS-1$
        }
        assertTrue(
                "SupportedAttribTypes.bom: should not have problem markers but has at least one:\n" //$NON-NLS-1$
                        + the1stProblem,
                the1stProblem == null);

        IFile okFile2 = getTestFile("SupportedConstructs.bom"); //$NON-NLS-1$

        problemMarkers = getProblemMarkers(okFile2);
        the1stProblem = null;
        if (problemMarkers.size() > 0) {
            ValidationsTestProblemMarkerInfo markerInfo = problemMarkers.get(0);
            the1stProblem = markerInfo.getProblemId() + "::" //$NON-NLS-1$
                    + markerInfo.getResourceURI() + "." //$NON-NLS-1$
                    + markerInfo.getLocationURI() + ":\n  \"" //$NON-NLS-1$
                    + markerInfo.getProblemText() + "\"\n"; //$NON-NLS-1$

			
			// Nikita ACE-7540 The max allowed count for searchable attributes changed form 15 to 30
			// Make sure we don't get a error level problem marker anymore for searchable attributes
			assertFalse("SupportedConstructs.bom should not have error level problem marker for searchble attributes",
						markerInfo.getProblemId() == "ace.bom.max.5.searchable");
        }
        assertTrue(
                "SupportedConstructs.bom: should not have problem markers but has at least one:\n" //$NON-NLS-1$
                        + the1stProblem,
                the1stProblem == null);

        /*
         * Then test the expected problems are raised
         */
        doTestValidations();

        return;
    }

    @Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos =
                new ValidationsTestProblemMarkerInfo[] {

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/NoSubPkgAllowed_EvenWhenNoCaseClasses.bom", //$NON-NLS-1$
                                "ace.bom.subpackage.issue", //$NON-NLS-1$
                                "_I_AFUGBVEemC_oi-pOXaww", //$NON-NLS-1$
                                "BPM  : Sub-packages are not supported (Sub-package not allowed (com.example.nosubpkgallowed_evenwhennocaseclasses))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.property.type", //$NON-NLS-1$
                                "_0yczoGAsEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for attributes (object (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8511 possibly because of ACE-8497 fix for migration, the migration of Integer -->
						 * Fixed Point Number is now working so shouldn't get this error.
						 * 
						 * This was due to Format-Version of UnsupportedAttribTypes being '6' as compared which caused
						 * non-migration
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom",
						// //$NON-NLS-1$
						// "ace.bom.illegal.property.type", //$NON-NLS-1$
						// "_baH5cGAsEemjK7MhjOTqUg", //$NON-NLS-1$
						// "BPM : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types
						// are supported for attributes (integer (com.example.unsupportedattribtypes))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.property.type", //$NON-NLS-1$
                                "_bKjzcGAsEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for attributes (ID (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.property.type", //$NON-NLS-1$
                                "_MsDigGAsEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for attributes (attachment (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.number.property.max.length", //$NON-NLS-1$
                                "_MU4twGAuEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Number attributes are restricted to 15 significant and decimal places in total (bad length number (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.property.type", //$NON-NLS-1$
                                "_NezOEGAsEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for attributes (duration (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.property.type", //$NON-NLS-1$
                                "_NJd3QGAsEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for attributes (date-time no timezone (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.primitive.type", //$NON-NLS-1$
                                "_y0kVMGAtEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for Primitive Type definitions (Attachement PrimitiveType (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.number.primitive.max.length", //$NON-NLS-1$
                                "_YwI1EGBQEemro8KSuFzoxg", //$NON-NLS-1$
                                "BPM  : Number primitive types are restricted to 15 significant and decimal places in total (Bad Length Primitive (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.primitive.type", //$NON-NLS-1$
                                "_z6Pj0GAtEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for Primitive Type definitions (Object PrimitiveType (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.primitive.type", //$NON-NLS-1$
                                "_zC328GAtEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for Primitive Type definitions (date-time no TZ PrimitiveType (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.primitive.type", //$NON-NLS-1$
                                "_zciUIGAtEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for Primitive Type definitions (ID PrimitiveType (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8511 possibly because of ACE-8497 fix for migration, the migration of Integer -->
						 * Fixed Point Number is now working so shouldn't get this error.
						 * 
						 * This was due to Format-Version of UnsupportedAttribTypes being '6' as compared which caused
						 * non-migration
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom",
						// //$NON-NLS-1$
						// "ace.bom.illegal.primitive.type", //$NON-NLS-1$
						// "_zqvvQGAtEemjK7MhjOTqUg", //$NON-NLS-1$
						// "BPM : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types
						// are supported for Primitive Type definitions (Integer PrimitiveType
						// (com.example.unsupportedattribtypes))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "ace.bom.illegal.primitive.type", //$NON-NLS-1$
                                "_zRorsGAtEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Only Text, Number, Date, Time, Date-Time with Timezone, URI and Boolean simple types are supported for Primitive Type definitions (Duration PrimitiveType (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "ace.bom.subpackage.issue", //$NON-NLS-1$
                                "_7jILUGAuEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Sub-packages are not supported (Sub-package (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8370 Composite id's now supported, so should not expect this problem marker any more.
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom",
						// //$NON-NLS-1$
						// "ace.bom.case.must.have.caseid", //$NON-NLS-1$
						// "_9kUfoGAxEemgPPDBEdhwDQ", //$NON-NLS-1$
						// "BPM : Case classes must have a single case identifier attribute (Unsupported Case Attribs
						// (no case state, composite attribs) (com.example.unsupportedconstructs))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

						/* Sid ACE-6504 Case-state is now automatically generated on migration from 4.x */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom",
						// //$NON-NLS-1$
						// "ace.bom.case.must.have.casestate", //$NON-NLS-1$
						// "_9kUfoGAxEemgPPDBEdhwDQ", //$NON-NLS-1$
						// "BPM : Case classes must have a case state attribute (Unsupported Case Attribs (no case
						// state, composite attribs) (com.example.unsupportedconstructs))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8511 possibly because of ACE-8497 fix for migration, the migration of Generalisation
						 * is now working so shouldn't get this error.
						 * 
						 * This was due to Format-Version of UnsupportedAttribTypes being '6' as compared which caused
						 * non-migration
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom",
						// //$NON-NLS-1$
						// "ace.bom.class.superclass", //$NON-NLS-1$
						// "_BNma0GAvEemjK7MhjOTqUg", //$NON-NLS-1$
						// "BPM : Super-classing / generalisation is not supported for classes (Invalid Class
						// Generalisation (com.example.unsupportedconstructs))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "ace.bom.caseid.in.case.only", //$NON-NLS-1$
                                "_F36BAWDjEemqb6fRqQJHQg", //$NON-NLS-1$
                                "BPM  : Only case classes can contain a case identifier attribute (textCaseId (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "casestate.invalid.containing.class.issue", //$NON-NLS-1$
                                "_F36BBGDjEemqb6fRqQJHQg", //$NON-NLS-1$
                                "BPM  : Only case classes can contain case state attributes (caseState1 (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

						/* Sid ACE-6504 Case-state is now automatically set to mandatory on migration from 4.x */
//                        new ValidationsTestProblemMarkerInfo(
//                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
//                                "ace.bom.casestate.must.be.mandatory.nonarray", //$NON-NLS-1$
//                                "_FPaRQmA0EemgPPDBEdhwDQ", //$NON-NLS-1$
//                                "BPM  : Case state attribute must be mandatory and non-array (multiplicity must be 1) (caseState1 (com.example.unsupportedconstructs))", //$NON-NLS-1$
//                                ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8369 Case Id's are now set to mandatory automatically on migration to 5.x - so
						 * problem marker will no longer exist...
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom",
						// //$NON-NLS-1$
						// "ace.bom.caseid.must.be.mandatory.nonarray", //$NON-NLS-1$
						// "_han0kWAyEemgPPDBEdhwDQ", //$NON-NLS-1$
						// "BPM : Case identifier attribute must be mandatory and non-array (multiplicity must be 1)
						// (textCaseId (com.example.unsupportedconstructs))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "ace.bom.caseid.in.case.only", //$NON-NLS-1$
                                "_KF_LAWDjEemqb6fRqQJHQg", //$NON-NLS-1$
                                "BPM  : Only case classes can contain a case identifier attribute (textCaseId (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "casestate.invalid.containing.class.issue", //$NON-NLS-1$
                                "_KF_LBGDjEemqb6fRqQJHQg", //$NON-NLS-1$
                                "BPM  : Only case classes can contain case state attributes (caseState1 (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8511 possibly because of ACE-8497 fixing bom formatVersion comparison check for
						 * migration the migration of Integer --> Fixed Point Number is now working so shouldn't get
						 * this error.
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom",
						// //$NON-NLS-1$
						// "ace.bom.class.operation", //$NON-NLS-1$
						// "_n4sLkGAvEemjK7MhjOTqUg", //$NON-NLS-1$
						// "BPM : Class operations are not supported (operationsAreUnsupported
						// (com.example.unsupportedconstructs))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8370 Composite id's now supported, so should not expect this problem marker any more.
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom",
						// //$NON-NLS-1$
						// "ace.bom.composite.caseid", //$NON-NLS-1$
						// "_OTl5UGAyEemgPPDBEdhwDQ", //$NON-NLS-1$
						// "BPM : Composite case identifier attributes are not supported (textCaseId
						// (com.example.unsupportedconstructs))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "ace.bom.searchable.must.be.nonarray", //$NON-NLS-1$
                                "_QkdBUGA1EemgPPDBEdhwDQ", //$NON-NLS-1$
                                "BPM  : Searchable attributes cannot be arrays (array searchable attrib2 (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "bom.cds.attribute.global.association.bidirectional.issue", //$NON-NLS-1$
                                "_RodPcGBKEem0apsFwpSXJg", //$NON-NLS-1$
                                "BPM  : Associations and Aggregations must be bidirectional. (Not -bi-directional (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

						/*
						 * Sid ACE-8370 Composite id's now supported, so should not expect this problem marker any more.
						 */
						// new ValidationsTestProblemMarkerInfo(
						// "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom",
						// //$NON-NLS-1$
						// "ace.bom.composite.caseid", //$NON-NLS-1$
						// "_SQfzwGAyEemgPPDBEdhwDQ", //$NON-NLS-1$
						// "BPM : Composite case identifier attributes are not supported (textCaseId2
						// (com.example.unsupportedconstructs))", //$NON-NLS-1$
						// ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedConstructs.bom", //$NON-NLS-1$
                                "ace.bom.enumeration.superclass", //$NON-NLS-1$
                                "_vHRuoGAuEemjK7MhjOTqUg", //$NON-NLS-1$
                                "BPM  : Super-classing is not supported for enumeration types (Invalid Enum Generalisation (com.example.unsupportedconstructs))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                        new ValidationsTestProblemMarkerInfo(
                                "/BPMProjectMigration_BOMValidations/Business Objects/UnsupportedAttribTypes.bom", //$NON-NLS-1$
                                "attributeTypeNotSet.issue", //$NON-NLS-1$
                                "_AmmKUHu8EemmA9mKLpVYNw", //$NON-NLS-1$
                                "BPM  : Attribute must have a type selected (undefinedTypeAttr (com.example.unsupportedattribtypes))", //$NON-NLS-1$
                                ""), //$NON-NLS-1$

                };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "AceBomMigrationValidationsTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.sce.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources = new TestResourceInfo[] {
                new TestResourceInfo("resources/AceBomMigrationValidationsTest", //$NON-NLS-1$
                        "BPMProjectMigration_BOMValidations/Business Objects{bom}/NoSubPkgAllowed_EvenWhenNoCaseClasses.bom"), //$NON-NLS-1$
                new TestResourceInfo("resources/AceBomMigrationValidationsTest", //$NON-NLS-1$
                        "BPMProjectMigration_BOMValidations/Business Objects{bom}/SupportedAttribTypes.bom"), //$NON-NLS-1$
                new TestResourceInfo("resources/AceBomMigrationValidationsTest", //$NON-NLS-1$
                        "BPMProjectMigration_BOMValidations/Business Objects{bom}/SupportedConstructs.bom"), //$NON-NLS-1$
                new TestResourceInfo("resources/AceBomMigrationValidationsTest", //$NON-NLS-1$
                        "BPMProjectMigration_BOMValidations/Business Objects{bom}/UnsupportedAttribTypes.bom"), //$NON-NLS-1$
                new TestResourceInfo("resources/AceBomMigrationValidationsTest", //$NON-NLS-1$
                        "BPMProjectMigration_BOMValidations/Business Objects{bom}/UnsupportedConstructs.bom"), //$NON-NLS-1$
        };

        return testResources;
    }

}
