/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.sce.tests.validation;

import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.ResourcesPlugin;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.util.TestUtil;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;
import com.tibco.xpd.resources.util.ProjectImporter;

/**
 * DQLValidationsTest
 * <p>
 * DQLValidationsTest - Test selected validations for DQL queries in bpm.caseData.findByCriteria() and
 * bpm.caseData.navigatebyCriteria() functions.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 *
 * @author aallway
 * @since August 2024
 */
public class DQLValidationsTest extends AbstractN2BaseValidationTest {

	public DQLValidationsTest() {
		super(true);
	}

	/**
	 * dqlValidationsTest
	 * 
	 * @throws Exception
	 */
	public void testDQLValidations() throws Exception
	{

		ProjectImporter projectImporter = TestUtil.importProjectsFromZip("com.tibco.xpd.sce.test", //$NON-NLS-1$
				new String[]{"resources/DQLValidationsTest/ACE7144Data/", //$NON-NLS-1$
						"resources/DQLValidationsTest/ACE7144ProcessValid/", //$NON-NLS-1$
						"resources/DQLValidationsTest/ACE7144ProcessInvalid/"}, //$NON-NLS-1$
				new String[]{"ACE7144Data", "ACE7144ProcessValid", "ACE7144ProcessInvalid"}); //$NON-NLS-1$//$NON-NLS-2$//$NON-NLS-3$

		assertTrue("Failed to load projects from \"resources/DQLValidationsTest/\"", //$NON-NLS-1$
				projectImporter != null);

		TestUtil.buildAndWait();

		/*
		 * Check espected validations are there.
		 */
		doTestValidations();

		/*
		 * Project with valid PSL Project Reference - so should have no problems.
		 */
		IProject ace7144ProcessValidProject = ResourcesPlugin.getWorkspace().getRoot()
				.getProject("ACE7144ProcessValid");
		assertFalse("ACE7144ProcessValid" //$NON-NLS-1$
				+ " project should not have any ERROR level problem markers but has: \n" //$NON-NLS-1$
				+ TestUtil.getErrorProblemMarkerList(ace7144ProcessValidProject, true),
				TestUtil.hasErrorProblemMarker(
						ace7144ProcessValidProject, // $NON-NLS-1$
						true, "dqlValidationsTest")); //$NON-NLS-1$

		projectImporter.performDelete();
	}

	@Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos = new ValidationsTestProblemMarkerInfo[] { 
    			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:100 column:123, DQL Query Error: The data type of the data field '${data.FloatingPointNumber}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:102 column:113, DQL Query Error: The multiplicity of the data field '${data.TimeArray}' does not match with the multiplicity of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:103 column:117, DQL Query Error: The multiplicity of the data field '${data.Address.times}' does not match with the multiplicity of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:107 column:127, DQL Query Error: The data type of the data field '${data.Address.houseNumber}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:108 column:126, DQL Query Error: The data type of the data field '${data.Address.roomnumber}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:109 column:120, DQL Query Error: The data type of the data field '${data.Address.date}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:110 column:120, DQL Query Error: The data type of the data field '${data.Address.time}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:111 column:122, DQL Query Error: The data type of the data field '${data.Address.addrId}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:112 column:138, DQL Query Error: The data type of the data field '${data.CustomerCase.additional.float1}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:114 column:115, DQL Query Error: The data type of the data field '${data.Address}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:115 column:117, DQL Query Error: The data type of the data field '${data.DateField}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:116 column:117, DQL Query Error: The data type of the data field '${data.TimeField}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:117 column:117, DQL Query Error: The data type of the data field '${data.TextField}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:118 column:124, DQL Query Error: The data type of the data field '${data.FixedPointNumber}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:119 column:127, DQL Query Error: The data type of the data field '${data.FloatingPointNumber}' does not match with the data type of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:12 column:126, DQL Query Error: The data type of the data field '${data.Address.houseNumber}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:121 column:121, DQL Query Error: The multiplicity of the data field '${data.DateTimeArray}' does not match with the multiplicity of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:122 column:125, DQL Query Error: The multiplicity of the data field '${data.Address.datetimes}' does not match with the multiplicity of the attribute 'orderLines[0].datetime'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:127 column:105, DQL Query Error: Syntax for the data field 'orderLines[${]' is not valid in the expression : orderLines[${].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:127 column:105, DQL Query Error: Right and left side braces used for the data fields are not matching in the given DQL string: orderLines[${].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
						""), //$NON-NLS-1$

				new ValidationsTestProblemMarkerInfo(
						"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$
						"bx.validateScriptTask", //$NON-NLS-1$
						"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$
						"BPM  : At Line:128 column:106, DQL Query Error: Syntax for the data field 'orderLines[${}]' is not valid in the expression : orderLines[${}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:129 column:118, DQL Query Error: Syntax for the data field 'orderLines[${badfieldspec}]' is not valid in the expression : orderLines[${badfieldspec}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:13 column:125, DQL Query Error: The data type of the data field '${data.Address.roomnumber}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:130 column:123, DQL Query Error: Data field specified '${data.UnknownField}' is not valid. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:131 column:135, DQL Query Error: Data field specified '${data.Address.unknownAttribute}' is not valid. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:134 column:127, DQL Query Error: Data field '${data.FixedPointNumber}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.FixedPointNumber}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:135 column:130, DQL Query Error: Data field '${data.FloatingPointNumber}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.FloatingPointNumber}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:136 column:129, DQL Query Error: Data field '${data.Address.roomnumber}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.Address.roomnumber}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:137 column:132, DQL Query Error: Data field '${data.Address.propertyValue}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.Address.propertyValue}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:14 column:119, DQL Query Error: The data type of the data field '${data.Address.date}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:140 column:120, DQL Query Error: Data field '${data.TextField}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.TextField}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:141 column:120, DQL Query Error: Data field '${data.DateField}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.DateField}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:142 column:120, DQL Query Error: Data field '${data.TimeField}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.TimeField}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:143 column:124, DQL Query Error: Data field '${data.DateTimeField}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.DateTimeField}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:144 column:125, DQL Query Error: Data field '${data.Address.addrId}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.Address.addrId}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:145 column:123, DQL Query Error: Data field '${data.Address.date}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.Address.date}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:146 column:123, DQL Query Error: Data field '${data.Address.time}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.Address.time}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:147 column:127, DQL Query Error: Data field '${data.Address.datetime}' used as array index must be an Integer (Number with zero decimal places) in expression : orderLines[${data.Address.datetime}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:15 column:119, DQL Query Error: The data type of the data field '${data.Address.time}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:150 column:123, DQL Query Error: Data field '${data.IntegerArray}' used as array index must be single valued in expression : orderLines[${data.IntegerArray}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:151 column:127, DQL Query Error: Data field '${data.Address.integers}' used as array index must be single valued in expression : orderLines[${data.Address.integers}].summary = 'abc' (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:155 column:98, DQL Query Error: Index should not be provided for the multi valued attribute 'orderLines' within the size() function. : orderLines[0] (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:156 column:117, DQL Query Error: Index should not be provided for the multi valued attribute 'orderadditional' within the size() function. : orderLines[0].orderadditional[1] (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:16 column:123, DQL Query Error: The data type of the data field '${data.Address.datetime}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:17 column:137, DQL Query Error: The data type of the data field '${data.CustomerCase.additional.float1}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:19 column:114, DQL Query Error: The data type of the data field '${data.Address}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:20 column:116, DQL Query Error: The data type of the data field '${data.DateField}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:21 column:116, DQL Query Error: The data type of the data field '${data.TimeField}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:22 column:120, DQL Query Error: The data type of the data field '${data.DateTimeField}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:23 column:123, DQL Query Error: The data type of the data field '${data.FixedPointNumber}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:24 column:126, DQL Query Error: The data type of the data field '${data.FloatingPointNumber}' does not match with the data type of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:26 column:116, DQL Query Error: The multiplicity of the data field '${data.TextArray}' does not match with the multiplicity of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:27 column:125, DQL Query Error: The multiplicity of the data field '${data.Address.additional}' does not match with the multiplicity of the attribute 'orderLines[0].summary'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:31 column:122, DQL Query Error: The data type of the data field '${data.Address.addrId}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:32 column:126, DQL Query Error: The data type of the data field '${data.Address.roomnumber}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:33 column:120, DQL Query Error: The data type of the data field '${data.Address.date}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:34 column:120, DQL Query Error: The data type of the data field '${data.Address.time}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:35 column:124, DQL Query Error: The data type of the data field '${data.Address.datetime}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:36 column:138, DQL Query Error: The data type of the data field '${data.CustomerCase.additional.float1}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:38 column:115, DQL Query Error: The data type of the data field '${data.Address}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:39 column:117, DQL Query Error: The data type of the data field '${data.DateField}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:40 column:117, DQL Query Error: The data type of the data field '${data.TimeField}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:41 column:121, DQL Query Error: The data type of the data field '${data.DateTimeField}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:42 column:117, DQL Query Error: The data type of the data field '${data.TextField}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:43 column:127, DQL Query Error: The data type of the data field '${data.FloatingPointNumber}' does not match with the data type of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:45 column:118, DQL Query Error: The multiplicity of the data field '${data.FixedArray}' does not match with the multiplicity of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:46 column:122, DQL Query Error: The multiplicity of the data field '${data.Address.fixeds}' does not match with the multiplicity of the attribute 'orderLines[0].quantity'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:50 column:123, DQL Query Error: The data type of the data field '${data.Address.houseNumber}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:51 column:118, DQL Query Error: The data type of the data field '${data.Address.addrId}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:52 column:116, DQL Query Error: The data type of the data field '${data.Address.date}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:53 column:116, DQL Query Error: The data type of the data field '${data.Address.time}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:54 column:120, DQL Query Error: The data type of the data field '${data.Address.datetime}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:55 column:133, DQL Query Error: The data type of the data field '${data.CustomerCase.additional.fixed}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:57 column:111, DQL Query Error: The data type of the data field '${data.Address}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:58 column:113, DQL Query Error: The data type of the data field '${data.DateField}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:59 column:113, DQL Query Error: The data type of the data field '${data.TimeField}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:6 column:130, DQL Query Error: Data field specified is not valid.   : ${data.Address.invalidProperty} (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:60 column:117, DQL Query Error: The data type of the data field '${data.DateTimeField}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:61 column:120, DQL Query Error: The data type of the data field '${data.FixedPointNumber}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:62 column:113, DQL Query Error: The data type of the data field '${data.TextField}' does not match with the data type of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:64 column:114, DQL Query Error: The multiplicity of the data field '${data.FloatArray}' does not match with the multiplicity of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:65 column:118, DQL Query Error: The multiplicity of the data field '${data.Address.floats}' does not match with the multiplicity of the attribute 'orderLines[0].cost'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:69 column:123, DQL Query Error: The data type of the data field '${data.Address.houseNumber}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:70 column:122, DQL Query Error: The data type of the data field '${data.Address.roomnumber}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:71 column:118, DQL Query Error: The data type of the data field '${data.Address.addrId}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:72 column:116, DQL Query Error: The data type of the data field '${data.Address.time}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:73 column:120, DQL Query Error: The data type of the data field '${data.Address.datetime}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:74 column:134, DQL Query Error: The data type of the data field '${data.CustomerCase.additional.float1}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:76 column:111, DQL Query Error: The data type of the data field '${data.Address}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:77 column:113, DQL Query Error: The data type of the data field '${data.TextField}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:78 column:113, DQL Query Error: The data type of the data field '${data.TimeField}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:79 column:117, DQL Query Error: The data type of the data field '${data.DateTimeField}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:8 column:119, DQL Query Error: Data field specified is not valid.   : ${data.InvalidField} (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:80 column:120, DQL Query Error: The data type of the data field '${data.FixedPointNumber}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:81 column:123, DQL Query Error: The data type of the data field '${data.FloatingPointNumber}' does not match with the data type of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:83 column:113, DQL Query Error: The multiplicity of the data field '${data.DateArray}' does not match with the multiplicity of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:84 column:117, DQL Query Error: The multiplicity of the data field '${data.Address.dates}' does not match with the multiplicity of the attribute 'orderLines[0].date'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:88 column:123, DQL Query Error: The data type of the data field '${data.Address.houseNumber}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:89 column:122, DQL Query Error: The data type of the data field '${data.Address.roomnumber}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:90 column:116, DQL Query Error: The data type of the data field '${data.Address.date}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:91 column:118, DQL Query Error: The data type of the data field '${data.Address.addrId}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:92 column:120, DQL Query Error: The data type of the data field '${data.Address.datetime}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:93 column:134, DQL Query Error: The data type of the data field '${data.CustomerCase.additional.float1}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:95 column:111, DQL Query Error: The data type of the data field '${data.Address}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:96 column:113, DQL Query Error: The data type of the data field '${data.DateField}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:97 column:113, DQL Query Error: The data type of the data field '${data.TextField}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:98 column:117, DQL Query Error: The data type of the data field '${data.DateTimeField}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_01BVgXGjEe-Haajej1owAw", //$NON-NLS-1$ 
						"BPM  : At Line:99 column:120, DQL Query Error: The data type of the data field '${data.FixedPointNumber}' does not match with the data type of the attribute 'orderLines[0].time'. (ACE7144ProcessInvalid:InvalidFieldRefs)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:12 column:101, DQL Query Error: Unknown attribute 'wrongAttributeName' from the data type 'com.example.ordermodel.new1::Address'. (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:14 column:119, DQL Query Error: Unknown attribute 'wrongNestedAttributeName' from the data type 'com.example.ordermodel.new1::OrderLine'. (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:16 column:123, DQL Query Error: Unknown attribute 'wrongNestedParent' from the data type 'com.example.ordermodel.new1::OrderLine'. (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:18 column:134, DQL Query Error: Unknown attribute 'invalidAttributeUnderSimpleType' from the data type 'Text'. (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:2 column:89, DQL Query Error: Value for Text attribute should be single-quoted: town = \"abc\" (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:21 column:103, DQL Query Error: Value is not appropriate for FixedPointNumber type: orderLines[0].quantity > abc (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:22 column:105, DQL Query Error: Value for FixedPointNumber attribute should not be quoted: orderLines[0].quantity > 'abc' (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:25 column:92, The Association Link Name parameter must identify a valid association (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:28 column:92, DQL Query Error: Unknown attribute 'badOrderAttributeName' from the data type 'com.example.ordermodel.new1::Order'. (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:31 column:125, DQL Query Error: Multi valued attribute 'orderLines' should be specified with an index: orderLines.quantity (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:34 column:131, DQL Query Error: Single valued attribute 'address' should not be specified with an index: address[0].houseNumber (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:37 column:130, DQL Query Error: Index must be an integer value : orderLines[xyz] (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:38 column:133, DQL Query Error: Spurious text is present after the end bracket : orderLines[xyz]abc (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:39 column:131, DQL Query Error: Index must be an integer value : orderLines[0][1] (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:42 column:130, DQL Query Error: Index value ALL is not supported : orderLines[ALL] (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:44 column:131, DQL Query Error: $ tag for index value is not supported : orderLines[$tag] (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
						"BPM  : At Line:47 column:143, DQL Query Error: DQL query parameter replacement ':maxQuantityParam' is no longer supported. You can use the data field directly using ${data.field}. : orderLines[0].quantity > :maxQuantityParam (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:5 column:132, DQL Query Error: DQL query no longer supports 'type of' operator.   : address1 type of 'com.example.ordermodel.new1.Address' (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:50 column:123, DQL Query Error: Unknown attribute 'anUnknownAttribute' from the data type 'com.example.ordermodel.new1::Order'. (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:51 column:143, DQL Query Error: Unknown attribute 'anUnknownNestedAttribute' from the data type 'com.example.ordermodel.new1::OrderLine'. (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:54 column:115, DQL Query Error: Attribute 'attribute1' is not searchable: attribute1 > 1 (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:55 column:126, DQL Query Error: Attribute 'partNum' is not searchable: orderLines[0].partNum > 1 (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:58 column:157, DQL Query Error: DQL query no longer supports 'type of' operator.   : orderTakers type of com.example.ordermodel.new1.Employee (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:8 column:93, DQL Query Error: Bad expression: garbage expression (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/ACE7144ProcessInvalid/Process Packages/ACE7144ProcessInvalid.xpdl", //$NON-NLS-1$ 
			    		"bx.validateScriptTask", //$NON-NLS-1$ 
			    		"_7TKltVDKEe-RuvrN0hdmJg", //$NON-NLS-1$ 
			    		"BPM  : At Line:9 column:105, DQL Query Error: Bad expression: orderLines [0] .quantity > 100 (ACE7144ProcessInvalid:Invalid)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			                
		};
        return markerInfos;
    }

    @Override
    protected String getTestName() {
		return "DQLValidationsTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.sce.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
		TestResourceInfo[] testResources = new TestResourceInfo[]{};
    
        return testResources;
    }


}
