<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://www.tibco.com/bs3.0/_wDLoACExEd-k6--qJNzXtQ" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="JScriptBrokenMapping" targetNamespace="http://www.tibco.com/bs3.0/_wDLoACExEd-k6--qJNzXtQ" tibex:XPDL="JScriptBrokenMapping.xpdl">
  <wsdl:types>
    <xsd:schema xmlns="http://www.tibco.com/bs3.0/_wDLoACExEd-k6--qJNzXtQ" targetNamespace="http://www.tibco.com/bs3.0/_wDLoACExEd-k6--qJNzXtQ"/>
  </wsdl:types>
</wsdl:definitions>
