<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:ns="http://www.tibco.com/bs3.0/_fnWPECEuEd-wY5wINe8d6A" xmlns:tibex="http://www.tibco.com/bs3.2/extensions" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="XPathBrokenMapping" targetNamespace="http://www.tibco.com/bs3.0/_fnWPECEuEd-wY5wINe8d6A" tibex:XPDL="XPathBrokenMapping.xpdl">
  <wsdl:types>
    <xsd:schema xmlns="http://www.tibco.com/bs3.0/_fnWPECEuEd-wY5wINe8d6A" targetNamespace="http://www.tibco.com/bs3.0/_fnWPECEuEd-wY5wINe8d6A"/>
  </wsdl:types>
</wsdl:definitions>
