/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import com.tibco.xpd.xpdl2.ModeType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.AssociatedParameter}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AssociatedParameterValidator {
    boolean validate();

    boolean validateFormalParam(String value);

    boolean validateMode(ModeType value);

    boolean validateDescription(String value);

    boolean validateMandatory(boolean value);

    boolean validateFormalParamId(String value);
}
