/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import com.tibco.xpd.xpdExtension.AuditEvent;
import org.eclipse.emf.common.util.EList;
import org.eclipse.emf.ecore.util.FeatureMap;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.Audit}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface AuditValidator {
    boolean validate();

    boolean validateAuditEvent(EList value);

    boolean validateAny(FeatureMap value);
}
