/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package com.tibco.xpd.xpdExtension.validation;

import com.tibco.xpd.xpdExtension.Visibility;
import com.tibco.xpd.xpdl2.TriggerResultMessage;
import com.tibco.xpd.xpdl2.TriggerType;

/**
 * A sample validator interface for {@link com.tibco.xpd.xpdExtension.StartMethod}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface StartMethodValidator {
    boolean validate();

    boolean validateTrigger(TriggerType value);

    boolean validateTriggerResultMessage(TriggerResultMessage value);

    boolean validateVisibility(Visibility value);
}
