/*
 * Copyright (c) TIBCO Software Inc 2004, 2008. All rights reserved.
 */
package com.tibco.xpd.n2.wp;

import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collection;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Properties;

import org.eclipse.core.resources.IFile;
import org.eclipse.core.resources.IProject;
import org.eclipse.core.resources.IResource;
import org.eclipse.core.runtime.IPath;
import org.eclipse.core.runtime.IStatus;
import org.eclipse.core.runtime.MultiStatus;
import org.eclipse.core.runtime.Path;
import org.eclipse.core.runtime.Status;
import org.eclipse.emf.common.util.BasicEList;
import org.eclipse.emf.common.util.URI;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.resource.Resource;
import org.eclipse.emf.ecore.resource.ResourceSet;
import org.eclipse.emf.ecore.resource.impl.ResourceSetImpl;
import org.osgi.framework.Version;

import com.tibco.bpm.dt.rasc.MicroService;
import com.tibco.n2.wp.archive.service.BusinessServiceType;
import com.tibco.n2.wp.archive.service.ChannelExtentionType;
import com.tibco.n2.wp.archive.service.ChannelType;
import com.tibco.n2.wp.archive.service.ChannelsType;
import com.tibco.n2.wp.archive.service.FormType;
import com.tibco.n2.wp.archive.service.PageActivityType;
import com.tibco.n2.wp.archive.service.PageFlowRefType;
import com.tibco.n2.wp.archive.service.PageFlowType;
import com.tibco.n2.wp.archive.service.ServiceArchiveDescriptorType;
import com.tibco.n2.wp.archive.service.WPFactory;
import com.tibco.n2.wp.archive.service.WorkTypeType;
import com.tibco.n2.wp.archive.service.util.WPResourceFactoryImpl;
import com.tibco.xpd.n2.bpel.utils.BPELN2Utils;
import com.tibco.xpd.n2.brm.utils.BRMUtils;
import com.tibco.xpd.n2.daa.utils.N2PENamingUtils;
import com.tibco.xpd.n2.resources.util.N2Utils;
import com.tibco.xpd.n2.wp.internal.Messages;
import com.tibco.xpd.n2.wp.utils.WPUtil;
import com.tibco.xpd.presentation.channels.AttributeValue;
import com.tibco.xpd.presentation.channels.Channel;
import com.tibco.xpd.presentation.channels.Channels;
import com.tibco.xpd.presentation.channels.ExtendedAttribute;
import com.tibco.xpd.presentation.channels.TypeAssociation;
import com.tibco.xpd.presentation.channeltypes.Attribute;
import com.tibco.xpd.presentation.channeltypes.AttributeType;
import com.tibco.xpd.presentation.channeltypes.ChannelDestination;
import com.tibco.xpd.presentation.resources.ui.internal.util.PresentationManager;
import com.tibco.xpd.processeditor.xpdl2.util.TaskObjectUtil;
import com.tibco.xpd.rasc.core.RascWriter;
import com.tibco.xpd.resources.WorkingCopy;
import com.tibco.xpd.resources.logger.Logger;
import com.tibco.xpd.resources.projectconfig.SpecialFolder;
import com.tibco.xpd.resources.util.SpecialFolderUtil;
import com.tibco.xpd.resources.util.WorkingCopyUtil;
import com.tibco.xpd.xpdExtension.FormImplementation;
import com.tibco.xpd.xpdExtension.FormImplementationType;
import com.tibco.xpd.xpdl2.Activity;
import com.tibco.xpd.xpdl2.Package;
import com.tibco.xpd.xpdl2.Process;
import com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil;

/**
 * Generates N2 deployment artifacts.
 * <p>
 * <i>Created: 10 Sep 2008</i>
 * </p>
 * 
 * @author Jan Arciuchiewicz
 */
public class WPGenerator {

    /**
     * The MicroServices to which the artifacts generated by this contributor
     * will be delivered.
     */
    private static final MicroService[] WP_MODEL_DESTINATION_SERVICES =
            { MicroService.WP };

    /**
     * Channel destination id for AMX-BPM.
     */
    private static final String AMXBPM_DESTINATION_ID = "amxbpm"; //$NON-NLS-1$

    protected static class GenerationContext {
        /** Maps channelId to Map of pageFlowId -> WPPageflow. */
        private final Map<String, Map<String, PageFlowType>> pageFlows =
                new HashMap<String, Map<String, PageFlowType>>();

        // cache for association between FormType and Activity or PageFlowType
        // and
        // PageFlow.
        private final Map<EObject, EObject> processRefMap =
                new HashMap<EObject, EObject>();

        private final List<IStatus> problems = new ArrayList<IStatus>();

        public List<IStatus> getProblems() {
            return problems;
        }

        private final String version;

        private final IProject project;

        public GenerationContext(IProject project, String version) {
            this.project = project;
            this.version = version;
        }

        public Map<String, PageFlowType> getPageFlows(String channelId) {
            Map<String, PageFlowType> channelPageFlows =
                    pageFlows.get(channelId);
            if (channelPageFlows == null) {
                channelPageFlows = new HashMap<String, PageFlowType>();
                pageFlows.put(channelId, channelPageFlows);
            }
            return channelPageFlows;
        }

        public IProject getProject() {
            return project;
        }

        public Map<EObject, EObject> getProcessRefMap() {
            return processRefMap;
        }

        /**
         * Sid ACE-1028 replaced get timestamp with the more useful get whole
         * version string.
         * 
         * @return This version is the Project 'time of RASC generation
         *         timestamped' version.
         */
        public String getProjectGenerationVersion() {
            return version;
        }

        /*
         * Sid ACE-1028 - additional functions for RASC relative output paths.
         */

        /**
         * @return The RASC base folder output for WP content (RASC /wp)
         */
        public IPath getBaseOutputRelativePath() {
            return new Path(WPUtil.SERVICE_ARCHIVE_DESC_ROOT_FOLDER_NAME);
        }

        /**
         * @return The RASC folder for output resources other than the WP model
         *         itself. CURRENTLY this is exactly the same as ther wpModel.wp
         *         file's folder as it was decided that no wp/<project
         *         version&timestamp>/ version folder was required because this
         *         version is available to WR in the RASC manifest anyway.). If
         *         necessary the version folder can be re-introduced by
         *         appending {@link #getProjectGenerationVersion()} as a new
         *         element after the base path.
         */
        public IPath getBaseResourcesOutputRelativePath() {
            return getBaseOutputRelativePath();
        }

    }

    private static final String CUSTOM_FORM_RELATIVE_PATH = "CUSTOM_FORM"; //$NON-NLS-1$

    /** */
    private static final Status PROBLEM_WARNING_STATUS =
            new Status(IStatus.WARNING, WPActivator.PLUGIN_ID,
                    Messages.WPGenerator_ProblemsWithWP_message2);

    /** Forms BOM Special Folder kind. */
    private static final String FORMS_BOM_FOLDER_KIND = "formsBOM"; //$NON-NLS-1$

    /** Forms GI Special Folder kind. */
    private static final String FORMS_GI_FOLDER_KIND = "formsGI"; //$NON-NLS-1$

    /** Forms GWT Special Folder kind. */
    private static final String FORMS_GWT_FOLDER_KIND = "formsGWT"; //$NON-NLS-1$

    /** Forms Mobile Special Folder kind. */
    private static final String FORMS_MOBILE_FOLDER_KIND = "formsMobile"; //$NON-NLS-1$

    private static final String BPEL_EXTENSION = "bpel"; //$NON-NLS-1$

    private static final Logger LOG = WPActivator.getDefault().getLogger();

    /** Work model ID prefix. */
    private static final String WORK_TYPE_ID_PREFIX = "WT_"; //$NON-NLS-1$

    /** Work presentation special folder kind. */
    public static final String WP_MODULES_SPECIAL_FOLDER_KIND = "wpOutput"; //$NON-NLS-1$

    /** Work presentation special folder name. */
    public static final String WP_MODULES_SPECIAL_FILDER_NAME = ".wpModules"; //$NON-NLS-1$

    /** Business resource management special folder kind. */
    public static final String BRM_MODULES_SPECIAL_FOLDER_KIND = "brmOutput"; //$NON-NLS-1$

    /** Business resource management special folder name. */
    public static final String BRM_MODULES_SPECIAL_FOLDER_NAME = ".brmModules"; //$NON-NLS-1$

    /** Name of the file containing work presentation descriptor. */
    private static final String WORK_PRESENTATION_DESCRIPTOR_NAME =
            WPUtil.SERVICE_ARCHIVE_DESC_NAME;

    /** XML file extension */
    private static final String XML_EXTENSION = "xml"; //$NON-NLS-1$

    private static final WPGenerator INSTANCE = new WPGenerator();

    private static final String PROPERTIES_EXTENSION = "properties"; //$NON-NLS-1$

    /**
     * AMX-BPM supporeted channel destinations.
     */
    private static final BasicEList<ChannelDestination> AMX_BPM_CHANNEL_DESTINATIONS =
            new BasicEList<ChannelDestination>(PresentationManager
                    .getChannelDestinationsByIds(AMXBPM_DESTINATION_ID));

    public static WPGenerator getInstance() {
        return INSTANCE;
    }

    /**
     * Private constructor. Use {@link #getInstance()} factory method instead.
     */
    private WPGenerator() {

    }

    /**
     * @param aProject
     * 
     * @return <code>true</code> the project might have content that we can
     *         generate deployment artifacts for.
     */
    public boolean projectHasRelevantContent(IProject aProject) {
        /*
         * We don't have to be 100% accurate and all content is derived from
         * process packages and their associated forms (see createWPDescriptor()
         * below, we potentially do stuff for User-Tasks, Business Services,
         * Case Actions and Pageflow processes.
         *
         * So rather than looking for all of these specifically, we can just say
         * 'if there are any process packages then there's a chance of some
         * contribution'
         */
        return !BRMUtils.getN2ProcessPackages(aProject).isEmpty();
    }

    /**
     * Generate work presentation module from Workforce Management Model without
     * using a job.
     * 
     * Adds the necessary content to the RASC via the given RASC writer
     * 
     * @param project
     *            the context project.
     * @param aWriter
     *            RASC artifacts writer
     * @param version
     *            the deployment RASC project version
     * 
     * @return IStatus
     */
    public IStatus generateN2Modules(final IProject project,
            RascWriter aRascWriter, String version) {

        GenerationContext ctx = new GenerationContext(project, version);

        ServiceArchiveDescriptorType wpDescriptor = createWPDescriptor(ctx);

        // Check if all channels are empty.
        // Don't create archive if all channels are empty.
        int allWorkTypesAssoc = 0;
        int allBusinessServices = 0;
        int allPageFlows = 0;
        for (ChannelType ch : wpDescriptor.getChannels().getChannel()) {
            allWorkTypesAssoc += ch.getWorkType().size();
            allBusinessServices += ch.getBusinessService().size();
            allPageFlows += ch.getPageFlow().size();
        }
        if (allWorkTypesAssoc + allBusinessServices + allPageFlows == 0) {
            return Status.OK_STATUS;
        }

        // Create EMF resource for descriptor.
        // Use private resource set.
        ResourceSet rs = new ResourceSetImpl();
        Resource descriptorResource = createWPDescriptorResource(wpDescriptor,
                ctx,
                rs);

        if (descriptorResource == null) {
            /* No Content? I guess the caller doesn't worry about this */
            return Status.OK_STATUS;
        }

        // Create archive and add all necessary artifacts in a proper layout.
        try {

            IPath descriptorPath = ctx.getBaseOutputRelativePath()
                    .append(WORK_PRESENTATION_DESCRIPTOR_NAME);

            OutputStream output =
                    aRascWriter.addContent(descriptorPath.toString(),
                    WORK_PRESENTATION_DESCRIPTOR_NAME,
                    WORK_PRESENTATION_DESCRIPTOR_NAME,
                    WP_MODEL_DESTINATION_SERVICES);


            // output the WP model to the rasc artifact
            descriptorResource.save(output, N2Utils.getDefaultXMLSaveOptions());

            // FORM-4691/XPD-3480: Deployable forms artefacts are now
            // contributed by FormCompositeContributor.

            creeateChannelPropertiesEntries(project, ctx,
                    aRascWriter);

        } catch (Exception e) {
            LOG.error(e);
            e.printStackTrace();
            return PROBLEM_WARNING_STATUS;
        } finally {

        }

        if (ctx.getProblems().isEmpty()) {
            return Status.OK_STATUS;
        } else {
            return new MultiStatus(WPActivator.PLUGIN_ID, 0,
                    ctx.getProblems()
                            .toArray(new IStatus[ctx.getProblems().size()]),
                    Messages.WPGenerator_ProblemsWithWP_message2, null);
        }
    }

    // JA: TODO this mapping should be replaced by an extension point
    // element defined in
    // 'com.tibco.xpd.presentation.resources.ui/channelTypes' extension.
    private static Map<String, String> CHANNELTYPE_TO_SF_MAP =
            new HashMap<String, String>();

    private static Map<String, String> PRESENTATION_TO_FORM_EXTENSION_MAP =
            new HashMap<String, String>();
    static {
        // XPD-4868 : Enable the workspace EMail Channel [uses GWT]
        CHANNELTYPE_TO_SF_MAP.put("EmailGIPush", FORMS_GWT_FOLDER_KIND); //$NON-NLS-1$
        CHANNELTYPE_TO_SF_MAP.put("openspaceEmailPush", FORMS_GWT_FOLDER_KIND); //$NON-NLS-1$
        CHANNELTYPE_TO_SF_MAP.put("GIGIPull", FORMS_GI_FOLDER_KIND); //$NON-NLS-1$
        CHANNELTYPE_TO_SF_MAP.put("openspaceGWTPull", FORMS_GWT_FOLDER_KIND); //$NON-NLS-1$
        CHANNELTYPE_TO_SF_MAP.put("MobileGWTPull", FORMS_MOBILE_FOLDER_KIND); //$NON-NLS-1$
        CHANNELTYPE_TO_SF_MAP.put("GIGWTPull", FORMS_GWT_FOLDER_KIND); //$NON-NLS-1$
        // TODO - to update when forms have completed their
        // XPD-4868 : Adding support of Workspace Email channel back, given the
        // GI forms are not supported any more for AMX-BPM and Workspace Email
        // is the only GI channel supported for AMX-BPM,
        // uses GWT in background, it is feasible/required to map GI to
        // 'gwt.json'
        PRESENTATION_TO_FORM_EXTENSION_MAP.put("GI", "gwt.json"); //$NON-NLS-1$ //$NON-NLS-2$
        PRESENTATION_TO_FORM_EXTENSION_MAP.put("GWT", "gwt.json"); //$NON-NLS-1$ //$NON-NLS-2$
    }

    private Map<String, String> getChannelTypeToSFMap() {
        return CHANNELTYPE_TO_SF_MAP;
    }

    private Map<String, String> getPresentationToFormExtensionMap() {
        return PRESENTATION_TO_FORM_EXTENSION_MAP;
    }

    private void creeateChannelPropertiesEntries(final IProject project,
            GenerationContext ctx, RascWriter aRascWriter)
            throws Exception, IOException {
        // Generate properties files.
        Channels projectChannels =
                PresentationManager.getInstance().getChannels(project);

        if (projectChannels != null) {
            for (Channel projectChannel : projectChannels.getChannels()) {
                for (TypeAssociation typeAssoc : projectChannel
                        .getTypeAssociations(AMX_BPM_CHANNEL_DESTINATIONS)) {
                    com.tibco.xpd.presentation.channeltypes.ChannelType projectChannelType =
                            typeAssoc.getChannelType();
                    if (projectChannelType != null) {

                        String channelID = projectChannelType.getId() + "_" //$NON-NLS-1$
                                + projectChannel.getName();

                        // All attr. of type: RESOURCE will have this path
                        // prepended (if it's not empty).
                        IPath resourcesPrefixPath =
                                ctx.getBaseResourcesOutputRelativePath();

                        Properties propetries = new Properties();

                        // Attributes. Get from type and overwrite later the
                        // default values.
                        for (Attribute attr : projectChannelType
                                .getAttributes()) {
                            String name = attr.getName();
                            String value = attr.getResolvedDefaultValue();
                            if (AttributeType.RESOURCE.equals(attr.getType())
                                    && isSet(value)) {
                                value = resourcesPrefixPath
                                        .append(nullSafe(value))
                                        .toPortableString();
                            }
                            if (name != null) {
                                propetries.setProperty(name, nullSafe(value));
                            }
                        }

                        for (AttributeValue attrValue : typeAssoc
                                .getAttributeValues()) {
                            String name = attrValue.getAttributeName();
                            String value = attrValue.getResolvedValue(true);
                            if (AttributeType.RESOURCE.equals(
                                    attrValue.getType()) && isSet(value)) {
                                value = resourcesPrefixPath
                                        .append(nullSafe(value))
                                        .toPortableString();
                            }
                            if (name != null) {
                                propetries.setProperty(name, nullSafe(value));
                            }
                        }

                        // Extended Attributes.
                        for (ExtendedAttribute extAttr : typeAssoc
                                .getExtendedAttributes()) {
                            if (extAttr.getName() != null) {
                                propetries.setProperty(extAttr.getName(),
                                        nullSafe(extAttr.getValue()));
                            }
                        }

                        /*
                         * Sid ACE-1028 Add content to RASC instead of file
                         * system
                         */
                        // Save properties to file for the channel.
                        String propertyFileName =
                                channelID + "." + PROPERTIES_EXTENSION; //$NON-NLS-1$
                        IPath propertyPath =
                                ctx.getBaseResourcesOutputRelativePath()
                                        .append(channelID)
                                        .append(propertyFileName);

                        OutputStream propertiesOutStream =
                                aRascWriter.addContent(propertyPath.toString(),
                                propertyFileName,
                                propertyFileName,
                                WP_MODEL_DESTINATION_SERVICES);


                        String message =
                                String.format("Properties for '%s' channel", //$NON-NLS-1$
                                        channelID);

                        propetries.store(propertiesOutStream, message);
                    }
                }
            }
        }
    }

    private String nullSafe(String value) {
        return value != null ? value : ""; //$NON-NLS-1$
    }

    private boolean isSet(String value) {
        return value != null && !value.trim().isEmpty();
    }


    /**
     * Gets the platform dependent form file.
     * 
     * @param activity
     *            A User Task activity referencing a Form
     * @return The form file or null.
     */
    private IFile getUserTaskChannelFormFile(Activity activity,
            ChannelType wpChannel) {
        IFile formFile = null;
        String channelTypeId =
                PresentationManager.getInstance().findChannelTypeIdByComponents(
                        wpChannel.getTargetChannelType().getLiteral(),
                        wpChannel.getPresentationChannelType().getLiteral(),
                        wpChannel.getImplementationType().getLiteral());

        /*
         * ChannelId contains the channel type id plus the description. We have
         * indexed the map with reference to the channel type ids. This
         * tokenizes to get the channel type id.
         */

        FormImplementation formImpl =
                TaskObjectUtil.getUserTaskFormImplementation(activity);
        IProject project = WorkingCopyUtil.getProjectFor(activity);
        String sfKind = getChannelTypeToSFMap().get(channelTypeId);
        SpecialFolder formsImplSF =
                SpecialFolderUtil.getSpecialFolderOfKind(project, sfKind);
        // Platform independent implementation.
        String formExtension = getPresentationToFormExtensionMap()
                .get(wpChannel.getPresentationChannelType().getLiteral());
        if (formImpl != null
                && FormImplementationType.FORM.equals(formImpl.getFormType())) {
            // User specified implementation.
            String url = formImpl.getFormURI();
            if (url != null) {
                if (url.startsWith(TaskObjectUtil.FORM_SCHEMA)) {
                    String path =
                            url.substring(TaskObjectUtil.FORM_SCHEMA.length());
                    if (formsImplSF != null
                            && formsImplSF.getFolder() != null) {
                        String formPath = (new Path(path)).removeFileExtension()
                                .addFileExtension(formExtension)
                                .toPortableString();
                        formFile = project.getFile(
                                formsImplSF.getFolder().getProjectRelativePath()
                                        .append(formPath).toString());
                    }
                }
            }
        } else if (formImpl == null) {
            // Default implementation.
            Process process = activity.getProcess();
            Package pkg = process.getPackage();
            if (formsImplSF != null && formsImplSF.getFolder() != null) {
                formFile = project.getFile(formsImplSF.getFolder()
                        .getProjectRelativePath().append(".default") //$NON-NLS-1$
                        .append(pkg.getName()).append(process.getName())
                        .append(activity.getName()).append(activity.getName())
                        .addFileExtension(formExtension).toString());
            }
        }

        return formFile;
    }

    /**
     * Creates N2 specific ServiceArchiveDescriptorType based on the provided
     * model.
     * 
     * @param timestamp
     * 
     * @param wmModel
     *            the source model.
     * @return the ServiceArchiveDescriptorType based on provided model.
     */
    private ServiceArchiveDescriptorType createWPDescriptor(
            GenerationContext ctx) {

        WPFactory f = WPFactory.eINSTANCE;
        ServiceArchiveDescriptorType wpDescriptor =
                f.createServiceArchiveDescriptorType();
        ChannelsType channelsType = f.createChannelsType();
        wpDescriptor.setChannels(channelsType);

        // Get project specific channel definition. Create WP descriptor
        // channels.
        List<ChannelType> wpChannels = new ArrayList<ChannelType>();
        Channels projectChannels =
                PresentationManager.getInstance().getChannels(ctx.getProject());
        if (projectChannels != null) {
            for (Channel projectChannel : projectChannels.getChannels()) {
                for (TypeAssociation typeAssoc : projectChannel
                        .getTypeAssociations(AMX_BPM_CHANNEL_DESTINATIONS)) {
                    com.tibco.xpd.presentation.channeltypes.ChannelType projectChannelType =
                            typeAssoc.getChannelType();
                    if (projectChannelType != null) {
                        ChannelType wpChannel = f.createChannelType();
                        String channelID = projectChannelType.getId() + "_" //$NON-NLS-1$
                                + projectChannel.getName();
                        wpChannel.setChannelId(channelID);
                        wpChannel.setName(projectChannel.getName());
                        wpChannel.setDescription(projectChannel.getName());
                        wpChannel.setTargetChannelType(
                                com.tibco.n2.common.channeltype.ChannelType
                                        .get(projectChannelType.getTarget()
                                                .getId()));
                        wpChannel.setPresentationChannelType(
                                com.tibco.n2.common.channeltype.PresentationType
                                        .get(projectChannelType
                                                .getPresentation().getId()));
                        wpChannel.setImplementationType(
                                com.tibco.n2.common.channeltype.ImplementationType
                                        .get(projectChannelType
                                                .getImplementation().getId()));
                        wpChannel.setDomain("");
                        wpChannel.setDefaultChannel(projectChannel.isDefault());
                        ChannelExtentionType channelExtention =
                                f.createChannelExtentionType();

                        channelExtention.setLocation(
                                new Path(channelID).toPortableString());
                        channelExtention.setFilename(new Path(channelID)
                                .addFileExtension(PROPERTIES_EXTENSION)
                                .toPortableString());
                        wpChannel.setExtensionConfig(channelExtention);
                        wpChannels.add(wpChannel);
                    }
                }
            }
        }
        Collection<Package> packages =
                BRMUtils.getN2ProcessPackages(ctx.getProject());
        Collection<Activity> manualN2Activities =
                BRMUtils.getN2ManualActivities(packages);
        Collection<Process> businessServices =
                BRMUtils.getBusinessServices(packages);
        Collection<Process> caseServices = BRMUtils.getCaseServices(packages);
        Collection<Process> standardPageFlows =
                BRMUtils.getStandardPageFlows(packages);

        for (ChannelType wpChannel : wpChannels) {

            // Manual activities on Process
            // Can by implemented as UserTask or Pageflow.
            for (Activity activity : manualN2Activities) {
                WorkTypeType wpWorkType = f.createWorkTypeType();

                wpWorkType.setGuid(WORK_TYPE_ID_PREFIX + activity.getId());
                wpWorkType.setName(activity.getName());
                wpWorkType.setVersion(ctx.getProjectGenerationVersion());

                FormImplementation userTaskFormImplementation =
                        TaskObjectUtil.getUserTaskFormImplementation(activity);
                // If userTastFormImplementation is 'null' then it means default
                // form option is selected.
                if (userTaskFormImplementation == null
                        || isFormUserTask(activity)) { // form
                    IFile formFile =
                            getUserTaskChannelFormFile(activity, wpChannel);
                    if (formFile == null) {
                        String msg = String.format(
                                Messages.WPGenerator_InvalidFormRef_message,
                                activity.getName());
                        LOG.error(msg);
                        ctx.getProblems().add(createWarnStatus(msg));
                    }
                    if (formFile != null && !formFile.exists()) {
                        String msg = String.format(
                                Messages.WPGenerator_FormNoExist_message,
                                formFile.getFullPath().toPortableString(),
                                activity.getName());
                        LOG.error(msg);
                        ctx.getProblems().add(createWarnStatus(msg));
                    }
                    FormType wpForm = f.createFormType();
                    String relativePath =
                            formFile != null
                                    ? getRelativePath(
                                            new Path(wpChannel.getChannelId()),
                                            formFile,
                                            ctx)
                                    : ""; //$NON-NLS-1$

                    wpForm.setRelativePath(relativePath);
                    wpForm.setName(formFile != null ? formFile.getName() : ""); //$NON-NLS-1$
                    wpForm.setFormIdentifier(new Path(relativePath)
                            .append(wpForm.getName()).toPortableString());

                    wpForm.setVersion(ctx.getProjectGenerationVersion());

                    wpWorkType.setForm(wpForm);
                    wpChannel.getWorkType().add(wpWorkType);
                    ctx.getProcessRefMap().put(wpForm, activity);

                } else if (isUserDefinedFormUserTask(activity)) { // custom form
                    FormImplementation formImplementation = TaskObjectUtil
                            .getUserTaskFormImplementation(activity);
                    FormType wpForm = f.createFormType();
                    wpForm.setName(formImplementation.getFormURI());
                    wpForm.setRelativePath(CUSTOM_FORM_RELATIVE_PATH);
                    wpForm.setFormIdentifier(formImplementation.getFormURI());
                    wpForm.setVersion(ctx.getProjectGenerationVersion());
                    wpWorkType.setForm(wpForm);
                    wpChannel.getWorkType().add(wpWorkType);
                    ctx.getProcessRefMap().put(wpForm, activity);

                } else if (isPageFlow(activity)) { // page flow
                    Process pageflowProcess =
                            TaskObjectUtil.getUserTaskPageflowProcess(activity);

                    if (pageflowProcess != null) {
                        // Check if page flow is in the same project.
                        WorkingCopy wc = WorkingCopyUtil
                                .getWorkingCopyFor(pageflowProcess);
                        IResource resource = wc.getEclipseResources().get(0);

                        if (resource == null || !ctx.getProject()
                                .equals(resource.getProject())) {
                            /*
                             * XPD-2608 : the code below for logging of the
                             * error message and also adding of warning message
                             * for cross project page flow reference is no
                             * longer required
                             */
                            // String message =
                            // String.format(Messages.WPGenerator_PageFlowFromOtherProject_message2,
                            // activity.getName());
                            // LOG.error(message);
                            // ctx.getProblems().add(createWarnStatus(message));
                            // continue;

                            /*
                             * XPD-2608 : add the other pageflow from cross
                             * project in the above standardPageFlows list to
                             * add the service:page-flow info in the wpModel.xml
                             */
                            IProject crossProject = resource.getProject();
                            Collection<Package> crossProjProcessPckgs =
                                    BRMUtils.getN2ProcessPackages(crossProject);
                            if (crossProjProcessPckgs.size() > 0) {
                                Collection<Process> crossProjStandardPageFlows =
                                        BRMUtils.getStandardPageFlows(
                                                crossProjProcessPckgs);
                                if (crossProjStandardPageFlows.size() > 0) {
                                    standardPageFlows
                                            .addAll(crossProjStandardPageFlows);
                                }
                            }
                        }

                        String pageFlowId = pageflowProcess.getId();
                        PageFlowType wpPageFlow =
                                ctx.getPageFlows(wpChannel.getChannelId())
                                        .get(pageFlowId);
                        if (wpPageFlow == null) {
                            wpPageFlow = f.createPageFlowType();
                            ctx.getPageFlows(wpChannel.getChannelId())
                                    .put(pageFlowId, wpPageFlow);
                            fillPageFlowType(wpPageFlow,
                                    pageflowProcess,
                                    wpChannel,
                                    ctx);
                        }
                        PageFlowRefType wpPageFlowRef =
                                f.createPageFlowRefType();
                        wpPageFlowRef.setRefId(pageFlowId);
                        wpWorkType.setPageFlowRef(wpPageFlowRef);
                        wpChannel.getWorkType().add(wpWorkType);
                    }
                }
            } // Manual activities on Process :END

            // Business services.
            for (Process businessService : businessServices) {
                BusinessServiceType wpBusinnesService =
                        f.createBusinessServiceType();
                fillPageFlowType(wpBusinnesService,
                        businessService,
                        wpChannel,
                        ctx);
                // Privileges are not added to business service. The privileges
                // to start business service are associated with the
                // "Start Business Service" model system action instead.
                wpChannel.getBusinessService().add(wpBusinnesService);
            }

            /* Add case services (CaseService is a Business Service) */
            for (Process caseService : caseServices) {

                BusinessServiceType wpCaseService =
                        f.createBusinessServiceType();
                fillPageFlowType(wpCaseService, caseService, wpChannel, ctx);
                wpChannel.getBusinessService().add(wpCaseService);
            }

            // Top level page flows.

            for (Process standardPageFlow : standardPageFlows) {
                String pageFlowId = standardPageFlow.getId();
                PageFlowType wpPageFlow = ctx
                        .getPageFlows(wpChannel.getChannelId()).get(pageFlowId);
                if (wpPageFlow == null) {
                    wpPageFlow = f.createPageFlowType();
                    ctx.getPageFlows(wpChannel.getChannelId()).put(pageFlowId,
                            wpPageFlow);
                    fillPageFlowType(wpPageFlow,
                            standardPageFlow,
                            wpChannel,
                            ctx);
                }
                wpChannel.getPageFlow().add(wpPageFlow);
            }
        }
        for (ChannelType wpChannel : wpChannels) {
            if (!wpChannel.getWorkType().isEmpty()
                    || !wpChannel.getBusinessService().isEmpty()
                    || !wpChannel.getPageFlow().isEmpty()) {
                // don't add empty channels
                channelsType.getChannel().add(wpChannel);
            }
        }
        return wpDescriptor;
    }

    private void fillPageFlowType(PageFlowType wpPageFlow,
            Process pageflowProcess, ChannelType wpChannel,
            GenerationContext ctx) {

        WPFactory f = WPFactory.eINSTANCE;
        WorkingCopy wc = WorkingCopyUtil.getWorkingCopyFor(pageflowProcess);
        if (wc == null) {
            LOG.error(String.format(
                    "PageFlow has to be contained inside a resource.", //$NON-NLS-1$
                    pageflowProcess.getName()));
        }
        IResource resource = wc.getEclipseResources().get(0);
        wpPageFlow.setId(pageflowProcess.getId());
        wpPageFlow.setName(pageflowProcess.getName());
        wpPageFlow.setModuleName(resource.getFullPath().toPortableString());

        /*
         * XPD-2608 : do not set time stamp or qualifier in the version if it is
         * a cross project reference
         */

        if (!ctx.getProject().equals(resource.getProject())) {
            /* XPD-2608 : remove .qualifier before setting the version */

            /*
             * TODO ACE-1005 Project Life-cycle governance
             * 
             * Sid ACE-1028 - GIVEN that there is a validation rule that has
             * always ensured that the process package version exactly matches
             * the project version THEN we should be able to get rid of the
             * process package version altogether and use the parent Project
             * version instead.
             */
            String pageflowProcessVersion =
                    Xpdl2ModelUtil.getProcessPackageVersionNumber(
                            pageflowProcess.getPackage());
            if (null != pageflowProcessVersion) {
                Version pageflowProjVer = new Version(pageflowProcessVersion);
                String qualifier = pageflowProjVer.getQualifier();
                if (null != qualifier && qualifier.length() > 0) {
                    String strVersion = pageflowProjVer.getMajor() + "." //$NON-NLS-1$
                            + pageflowProjVer.getMinor() + "." //$NON-NLS-1$
                            + pageflowProjVer.getMicro();
                    wpPageFlow.setModuleVersion(strVersion);
                } else {
                    wpPageFlow.setModuleVersion(pageflowProcessVersion);
                }
            }

        } else {

            wpPageFlow.setModuleVersion(
                    getModuleVersionForLocalProjectPackage(pageflowProcess.getPackage(),
                            ctx));
        }

        String xpdlFileName = WorkingCopyUtil.getWorkingCopyFor(pageflowProcess)
                .getEclipseResources().get(0).getName();
        wpPageFlow.setUrl(new Path(resource.getProject().getName())
                .append(N2PENamingUtils.COMPOSITE_OUTPUTFOLDER_NAME)
                .append(BPELN2Utils.BPEL_ROOT_OUTPUTFOLDER_NAME)
                .append(BPELN2Utils.PF_OUTPUTFOLDER_NAME).append(xpdlFileName)
                .append(pageflowProcess.getName())
                .addFileExtension(BPEL_EXTENSION).toPortableString());

        // processRefMap.put(wpPageFlow, pageflowProcess);

        /*
         * XPD-5783 : Do not add 'page-activity' information if there is a cross
         * project dependency.
         */
        if (ctx.getProject().equals(resource.getProject())) {
            Collection<Activity> userTasks =
                    BRMUtils.getManualPageFlowActivities(pageflowProcess);
            for (Activity pfActivity : userTasks) {
                PageActivityType pageActivityType = f.createPageActivityType();
                pageActivityType.setId(pfActivity.getId());
                pageActivityType.setName(pfActivity.getName());

                FormType wpForm = f.createFormType();
                FormImplementation userTaskFormImplementation = TaskObjectUtil
                        .getUserTaskFormImplementation(pfActivity);
                // If userTastFormImplementation is 'null' then it means default
                // form option is selected.
                if (userTaskFormImplementation == null
                        || isFormUserTask(pfActivity)) {
                    IFile pfActivityFormFile =
                            getUserTaskChannelFormFile(pfActivity, wpChannel);

                    if (pfActivityFormFile == null) {
                        String message = String.format(
                                Messages.WPGenerator_InvalidFormRef_message,
                                pfActivity.getName());
                        LOG.error(message);
                        ctx.getProblems().add(createWarnStatus(message));
                    }
                    if (pfActivityFormFile != null
                            && !pfActivityFormFile.exists()) {
                        String message = String.format(
                                Messages.WPGenerator_FormNoExist_message,
                                pfActivityFormFile.getFullPath()
                                        .toPortableString(),
                                pfActivity.getName());
                        LOG.error(message);
                        ctx.getProblems().add(createWarnStatus(message));
                    }

                    String relativePath =
                            pfActivityFormFile != null
                                    ? getRelativePath(
                                            new Path(wpChannel.getChannelId()),
                                            pfActivityFormFile,
                                            ctx)
                                    : ""; //$NON-NLS-1$
                    wpForm.setRelativePath(relativePath);
                    wpForm.setName(pfActivityFormFile != null
                            ? pfActivityFormFile.getName()
                            : ""); //$NON-NLS-1$
                    wpForm.setVersion(ctx.getProjectGenerationVersion());
                    wpForm.setFormIdentifier(new Path(relativePath)
                            .append(wpForm.getName()).toPortableString());
                    pageActivityType.setPageReference(wpForm);
                    ctx.getProcessRefMap().put(wpForm, pfActivity);
                    wpPageFlow.getPageActivity().add(pageActivityType);
                } else if (isUserDefinedFormUserTask(pfActivity)) {
                    FormImplementation formImplementation = TaskObjectUtil
                            .getUserTaskFormImplementation(pfActivity);
                    wpForm.setName(formImplementation.getFormURI());
                    wpForm.setVersion(ctx.getProjectGenerationVersion());
                    wpForm.setRelativePath(CUSTOM_FORM_RELATIVE_PATH);
                    wpForm.setFormIdentifier(formImplementation.getFormURI());
                    pageActivityType.setPageReference(wpForm);
                    ctx.getProcessRefMap().put(wpForm, pfActivity);
                    wpPageFlow.getPageActivity().add(pageActivityType);
                }
            }
        }
    }

    /**
     * Get the module version to use for dependencies on process package in the
     * local project.
     * 
     * @param xpdlPackage
     * @param ctx
     * 
     * @return the module version to use for dependencies on process package in
     *         the local project.
     */
    private String getModuleVersionForLocalProjectPackage(Package xpdlPackage,
            GenerationContext ctx) {
        /*
         * Sid ACE-1028. There are validation rules to force Process Package
         * versions to be exactly the same version as the project
         * 
         * THis function USED to get the process package version and replace
         * it's qualifier with the same qualifier as the 'DAA generation
         * timestamp'
         * 
         * Therefore it must have always been EXACTLY the same as the project's
         * RASC generation version+timestamp
         * 
         * So we can just use that.
         */
        return ctx.getProjectGenerationVersion();
    }

    private boolean isFormUserTask(Activity activity) {
        FormImplementation formImplementation =
                TaskObjectUtil.getUserTaskFormImplementation(activity);
        if (formImplementation != null && FormImplementationType.FORM
                .equals(formImplementation.getFormType())) {
            return true;
        }
        return false;
    }

    private boolean isUserDefinedFormUserTask(Activity activity) {
        FormImplementation formImplementation =
                TaskObjectUtil.getUserTaskFormImplementation(activity);
        if (formImplementation != null && FormImplementationType.USER_DEFINED
                .equals(formImplementation.getFormType())) {
            return true;
        }
        return false;
    }

    private boolean isPageFlow(Activity activity) {
        FormImplementation formImplementation =
                TaskObjectUtil.getUserTaskFormImplementation(activity);
        if (formImplementation != null && FormImplementationType.PAGEFLOW
                .equals(formImplementation.getFormType())) {
            return true;
        }
        return false;
    }

    /**
     * Generate work presentation descriptor resource in the context of the
     * provided resource set.
     * 
     * @param wmModel
     *            the source model.
     * @param ctx
     *            The generation context
     * @param rs
     *            context resource set for generated resources <code>null</code>
     *            if resource should not be generated (all channels are empty).
     */
    private Resource createWPDescriptorResource(
            ServiceArchiveDescriptorType wpDescriptor, GenerationContext ctx,
            ResourceSet rs) {

        Map<String, Object> extensionToFactoryMap =
                Resource.Factory.Registry.INSTANCE.getExtensionToFactoryMap();
        Object previousXMLFactory = extensionToFactoryMap.get(XML_EXTENSION);
        extensionToFactoryMap.put(XML_EXTENSION, new WPResourceFactoryImpl());

        // create work presentation resource

        extensionToFactoryMap.put(XML_EXTENSION, new WPResourceFactoryImpl());
        try {
            com.tibco.n2.wp.archive.service.DocumentRoot docRoot =
                    WPFactory.eINSTANCE.createDocumentRoot();
            docRoot.setServiceArchiveDescriptor(wpDescriptor);

            /*
             * Sid ACE-1028 - we're outputing streams to RASC now so don't need
             * full paths etc.
             */
            String filePath = ctx.getBaseOutputRelativePath()
                    .append(WORK_PRESENTATION_DESCRIPTOR_NAME)
                    .toString();

            URI resourceURI = URI.createURI(filePath);

            Resource workPresentationResource = rs.createResource(resourceURI);
            workPresentationResource.getContents().add(docRoot);
            return workPresentationResource;

        } finally {
            extensionToFactoryMap.put(XML_EXTENSION, previousXMLFactory);
        }
    }

    private String getRelativePath(IPath path, IFile formFile,
            GenerationContext ctx) {
        IPath projectRelativePath = formFile.getProjectRelativePath();
        projectRelativePath = projectRelativePath.removeLastSegments(1);
        int fragmentsToRemove = 2;
        projectRelativePath =
                projectRelativePath.removeFirstSegments(fragmentsToRemove);


        projectRelativePath = path
                .append(projectRelativePath);
        String toReturn = projectRelativePath.toPortableString();
        return toReturn;
    }

    private IStatus createWarnStatus(String message) {
        return new Status(IStatus.WARNING, WPActivator.PLUGIN_ID, message);
    }

}
