/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.validation.wm.test;

import java.util.Collection;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import org.eclipse.core.resources.IResource;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.AbstractBaseExtendedValidationTest;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.processeditor.xpdl2.util.ProcessScriptUtil;
import com.tibco.xpd.resources.WorkingCopy;
import com.tibco.xpd.resources.XpdResourcesPlugin;
import com.tibco.xpd.xpdl2.Activity;
import com.tibco.xpd.xpdl2.Package;
import com.tibco.xpd.xpdl2.Process;
import com.tibco.xpd.xpdl2.util.Xpdl2ModelUtil;

/**
 * WorkItemScriptValidationTest
 * <p>
 * WorkItemScriptValidationTest - Test selected validations are correctly
 * raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 * 
 * 
 * 
 * @author
 * @since
 */
public class WorkItemScriptValidationTest extends
        AbstractBaseExtendedValidationTest {

    public WorkItemScriptValidationTest() {
        super(true);
    }

    /**
     * WorkItemScriptValidationTest
     * 
     * @throws Exception
     */
    public void testWorkItemScriptValidationTest() throws Exception {
        doTestValidations();
        return;
    }

    @Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos =
                new ValidationsTestProblemMarkerInfo[] {

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:1 column:41, Property cancela is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:10 column:85, Method getName is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:13 column:37, Method listIterator is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:14 column:39, Method getActivityIds is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:15 column:47, Property lengths is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:16 column:16, Method next is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:18 column:67, Method listIterator is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:2 column:47, Method getContexts is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:22 column:51, Method getAlias is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:23 column:54, Method getAlias is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:24 column:46, Method next is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:3 column:49, Method getActivityId is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:4 column:60, Method toLowerCase is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:5 column:60, Property length is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:6 column:62, Method cclear is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:7 column:75, Method get is not applicable for the provided argument types (String) (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:8 column:66, Method set is not applicable for the provided number of arguments  (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.error.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:9 column:68, Method getPositions is invalid for the current context (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.warning.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:10 column:85, Unable to determine type, operation may not be supported and content assist will not be available (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/WorkItemScriptValidation/Process Packages/WorkItemScriptValidation.xpdl", //$NON-NLS-1$ 
                                "bx.warning.userTaskOpenScript", //$NON-NLS-1$ 
                                "_TZklAFnhEd-4-bg0r4Cp5A", //$NON-NLS-1$ 
                                "Process Manager 1.x : OpenScript::At Line:24 column:46, Unable to determine type, operation may not be supported and content assist will not be available (WorkItemScriptValidationProcess:InvalidWorkItemScripts)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$                 
                };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "WorkItemScriptValidationTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.validation.wm.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources =
                new TestResourceInfo[] { new TestResourceInfo(
                        "resources/WorkItemScriptValidation", "WorkItemScriptValidation/Process Packages{processes}/WorkItemScriptValidation.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
                };

        return testResources;
    }

    @Override
    protected Set<String> getAffectedIds(IResource resource) {
        if (resource != null) {
            WorkingCopy wc =
                    XpdResourcesPlugin.getDefault().getWorkingCopy(resource);
            if (wc.getRootElement() instanceof Package) {
                Package model = (Package) wc.getRootElement();
                assertNotNull("Root element of the model is null even after migration", //$NON-NLS-1$
                        model);
                if (model != null) {
                    List<Process> processes = model.getProcesses();
                    if (processes != null) {
                        Set<String> affectedIds = new HashSet<String>();
                        for (Process process : processes) {
                            Collection<Activity> activities =
                                    Xpdl2ModelUtil
                                            .getAllActivitiesInProc(process);
                            if (activities != null) {
                                for (Activity activity : activities) {
                                    if (activity != null
                                            && ProcessScriptUtil
                                                    .isUserTaskWithOpenScriptType(activity,
                                                            "JavaScript")) {//$NON-NLS-1$
                                        affectedIds.add(activity.getId());
                                    }
                                }
                            }
                        }
                        return affectedIds;
                    }
                }
            }
        }
        return Collections.emptySet();
    }

    @Override
    protected boolean shouldTestUnregisteredErrors(TestResourceInfo testResource) {
        if (testResource != null && testResource.getTokenisedPath() != null
                && testResource.getTokenisedPath().endsWith(".xpdl")) {//$NON-NLS-1$
            return true;
        }
        return false;
    }

}
