<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="CUSTOMER"
        targetNamespace="http://test/j2c/jdbc/customer"
        xmlns:tns="http://test/j2c/jdbc/customer"
        xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns:datans="http://test/j2c/jdbc/customer">
        <wsdl:types>
                <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
                        <xsd:import namespace="http://test/j2c/jdbc/customer"
                                schemaLocation="approval_management.xsd">
                        </xsd:import>
                </xsd:schema>
        </wsdl:types>
        <wsdl:message name="CUSTOMERRequest">
                <wsdl:part name="request" element="datans:CUSTOMER"></wsdl:part>
        </wsdl:message>
        <wsdl:portType name="Customer">
                <wsdl:operation name="updateCustomer">
                        <wsdl:input message="tns:CustomerRequest"></wsdl:input>
                        <wsdl:output message="tns:CustomerRequest"></wsdl:output>
                </wsdl:operation>
                <wsdl:operation name="createCustomer">
                        <wsdl:input message="tns:CustomerRequest"></wsdl:input>
                        <wsdl:output message="tns:CustomerRequest"></wsdl:output>
                </wsdl:operation>
                <wsdl:operation name="retrieveCustomer">
                        <wsdl:input message="tns:CustomerRequest"></wsdl:input>
                        <wsdl:output message="tns:CustomerRequest"></wsdl:output>
                </wsdl:operation>
        </wsdl:portType>
</wsdl:definitions>
