/*
 * Copyright (c) TIBCO Software Inc 2004, 2007. All rights reserved.
 */
package com.tibco.xpd.validation;

import java.util.Collection;
import java.util.Collections;

import org.eclipse.core.resources.IResource;

import com.tibco.xpd.validation.provider.IIssue;

/**
 * A ValidationEvent is generated at the end of each validation run and is
 * reported to registered IValidationListener classes.
 * 
 * @author nwilson
 */
public class ValidationEvent {

    /** Collection of all issues generated by this validation run. */
    private final Collection<IIssue> isues;

    /** The resource being validated. */
    private final IResource resource;

    /**
     * @param resource The resource being validated.
     * @param isues Collection of issues.
     */
    public ValidationEvent(IResource resource, Collection<IIssue> isues) {
        this.resource = resource;
        this.isues = Collections.unmodifiableCollection(isues);
    }
    
    /**
     * @return the issues
     */
    public Collection<IIssue> getIsues() {
        return isues;
    }
    
    /**
     * @return the resource
     */
    public IResource getResource() {
        return resource;
    }
}
