<?xml version="1.0" encoding="UTF-8"?>
<definitions xmlns="http://schemas.xmlsoap.org/wsdl/"
	xmlns:ns0="http://tibco.com/amx/integration/test/wsdl/firstimportschema"
	xmlns:tns="http://tibco.com/amx/integration/test/wsdl/messages"
	xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="MessageWSDL"
	targetNamespace="http://tibco.com/amx/integration/test/wsdl/messages">

	<!-- This works when we have a schema imported via a types definition -->
	<types>
		<xsd:schema>
			<xsd:import schemaLocation="FirstImportSchema.xsd"
				namespace="http://tibco.com/amx/integration/test/wsdl/firstimportschema"></xsd:import>
		</xsd:schema>
	</types>
	
	<!-- However, at the moment there are problems with this one: -->
	<!-- <import location="FirstImportSchema.xsd"
		namespace="http://tibco.com/amx/integration/test/wsdl/firstimportschema" /> -->
		
	<message name="WsdlImport_InMsg">
		<part name="PurchaseOrderRequest_Type" type="ns0:CT_PurchaseOrderRequest" />
	</message>
	<message name="WsdlImport_OutMsg">
		<part name="PurchaseOrderResponse_Type" type="ns0:CT_PurchaseOrderResponse" />
	</message>
</definitions>
