/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.n2.mappings.validation.test;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;

/**
 * JSInvalidModeTest
 * <p>
 * JSInvalidModeTest - Test selected validations are correctly raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 * 
 * 
 * 
 * @author
 * @since
 */
public class N2_06_JSInvalidModeTest extends AbstractN2BaseValidationTest {

    public N2_06_JSInvalidModeTest() {
        super(true);
    }

    /**
     * JSInvalidModeTest
     * 
     * @throws Exception
     */
    public void testJSInvalidModeTest() throws Exception {
        doTestValidations();
        return;
    }

    @Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos =
                new ValidationsTestProblemMarkerInfo[] {

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.8/@event/@triggerResultMessage/@message/@dataMappings.11", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter performerPOut (JSInvalidModeMapped:StartRequestOnly:performerPOut)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.8/@event/@triggerResultMessage/@message/@dataMappings.12", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter textPout (JSInvalidModeMapped:StartRequestOnly:textPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.1", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter booleanPinout (JSInvalidModeMapped:CatchIntermediateMessageEvent:booleanPinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.3", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter datePinout (JSInvalidModeMapped:CatchIntermediateMessageEvent:datePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.8/@event/@triggerResultMessage/@message/@dataMappings.5", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter dateTimePinout (JSInvalidModeMapped:StartRequestOnly:dateTimePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.5", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter dateTimePinout (JSInvalidModeMapped:CatchIntermediateMessageEvent:dateTimePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.8/@event/@triggerResultMessage/@message/@dataMappings.7", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter decimalPout (JSInvalidModeMapped:StartRequestOnly:decimalPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.7", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter decimalPout (JSInvalidModeMapped:CatchIntermediateMessageEvent:decimalPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.8/@event/@triggerResultMessage/@message/@dataMappings.1", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter booleanPinout (JSInvalidModeMapped:StartRequestOnly:booleanPinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.9", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter integerPout (JSInvalidModeMapped:CatchIntermediateMessageEvent:integerPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.8/@event/@triggerResultMessage/@message/@dataMappings.3", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter datePinout (JSInvalidModeMapped:StartRequestOnly:datePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.3", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter datePinout (JSInvalidModeMapped:StartRequestResponse:datePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskReceive/@message/@dataMappings.1", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter booleanPinout (JSInvalidModeMapped:ReceiveTask:booleanPinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.1", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter booleanPinout (JSInvalidModeMapped:StartRequestResponse:booleanPinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskReceive/@message/@dataMappings.3", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter datePinout (JSInvalidModeMapped:ReceiveTask:datePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskReceive/@message/@dataMappings.9", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter integerPout (JSInvalidModeMapped:ReceiveTask:integerPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.9", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter integerPout (JSInvalidModeMapped:StartRequestResponse:integerPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.7", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter decimalPout (JSInvalidModeMapped:StartRequestResponse:decimalPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskReceive/@message/@dataMappings.5", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter dateTimePinout (JSInvalidModeMapped:ReceiveTask:dateTimePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.5", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter dateTimePinout (JSInvalidModeMapped:StartRequestResponse:dateTimePinout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskReceive/@message/@dataMappings.7", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter decimalPout (JSInvalidModeMapped:ReceiveTask:decimalPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.8/@event/@triggerResultMessage/@message/@dataMappings.9", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter integerPout (JSInvalidModeMapped:StartRequestOnly:integerPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.11", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter performerPOut (JSInvalidModeMapped:StartRequestResponse:performerPOut)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.13", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter textPout (JSInvalidModeMapped:StartRequestResponse:textPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.11", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter performerPOut (JSInvalidModeMapped:CatchIntermediateMessageEvent:performerPOut)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.13", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter textPout (JSInvalidModeMapped:CatchIntermediateMessageEvent:textPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskReceive/@message/@dataMappings.11", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter performerPOut (JSInvalidModeMapped:ReceiveTask:performerPOut)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/JavascriptMappingsTest/Process Packages/JSInvalidModeMapped.xpdl", //$NON-NLS-1$ 
                                "bpmn.dev.mappingModeError", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskReceive/@message/@dataMappings.13", //$NON-NLS-1$ 
                                "BPMN : Invalid MODE type OUT for the mapped parameter textPout (JSInvalidModeMapped:ReceiveTask:textPout)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "JSInvalidModeTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.n2.mappings.validation.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources =
                new TestResourceInfo[] {
                        new TestResourceInfo(
                                "resources/JSInvalidModeTest", "JavascriptMappingsTest/Process Packages{processes}/JSInvalidModeMapped.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
                        new TestResourceInfo(
                                "resources/JSInvalidModeTest", "JavascriptMappingsTest/Service Descriptors{wsdl}/SimpleXSD.wsdl"), //$NON-NLS-1$ //$NON-NLS-2$
                };

        return testResources;
    }

}
