/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.n2.mappings.validation.test;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;

/**
 * XpathBrokenMappingsValidationTest
 * <p>
 * XpathBrokenMappingsValidationTest - Test selected validations are correctly
 * raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 * 
 * 
 * 
 * @author
 * @since
 */
public class N2_09_XpathBrokenMappingsValidationTest extends
        AbstractN2BaseValidationTest {

    public N2_09_XpathBrokenMappingsValidationTest() {
        super(true);
    }

    /**
     * XpathBrokenMappingsValidationTest
     * 
     * @throws Exception
     */
    public void testXpathBrokenMappingsValidationTest() throws Exception {
        doTestValidations();
        return;
    }

    @Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos =
                new ValidationsTestProblemMarkerInfo[] {

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.sourceMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.0/@implementation/@taskReceive/@message/@dataMappings.0", //$NON-NLS-1$ 
                                "Process Manager 1.x : Input To Process: mapping source data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:ReceiveTask:P4)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.sourceMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.7/@event/@resultError/@otherElements.1/@message/@dataMappings.0", //$NON-NLS-1$ 
                                "Process Manager 1.x : Map From Error: mapping source data 'wso:/fault:fault/part:F4' is no longer available. (XPathBrokenMappingProcess:null:P7)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.targetMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.2/@implementation/@taskService/@messageIn/@dataMappings.0", //$NON-NLS-1$ 
                                "Process Manager 1.x : Input To Service: mapping target data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:ServiceTask:wso:/part:P4)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.targetMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.6/@event/@triggerResultMessage/@message/@dataMappings.0", //$NON-NLS-1$ 
                                "Process Manager 1.x : Output From Process: mapping target data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:ReplyToCatchIntermediateMessageEvent:wso:/part:P4)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.sourceMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.3/@event/@triggerResultMessage/@message/@dataMappings.0", //$NON-NLS-1$ 
                                "Process Manager 1.x : Input To Process: mapping source data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:StartEvent:P4)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.sourceMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.2/@implementation/@taskService/@messageOut/@dataMappings.1", //$NON-NLS-1$ 
                                "Process Manager 1.x : Output From Service: mapping source data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:ServiceTask:P7)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.targetMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.4/@event/@triggerResultMessage/@message/@dataMappings.0", //$NON-NLS-1$ 
                                "Process Manager 1.x : Output From Process: mapping target data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:EndEvent:wso:/part:P4)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.targetMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.1/@implementation/@taskSend/@message/@dataMappings.1", //$NON-NLS-1$ 
                                "Process Manager 1.x : Output From Process: mapping target data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:ReplyToReceiveTask:wso:/part:P4)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/BrokenMappingsTest/Process Packages/XPathBrokenMapping.xpdl", //$NON-NLS-1$ 
                                "abstractMappingRule.sourceMissing", //$NON-NLS-1$ 
                                "//@package/@processes.0/@activities.5/@event/@triggerResultMessage/@message/@dataMappings.0", //$NON-NLS-1$ 
                                "Process Manager 1.x : Input To Process: mapping source data 'wso:/part:P4' is no longer available. (XPathBrokenMappingProcess:CatchIntermediateMessageEvent:P4)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "XpathBrokenMappingsValidationTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return Activator.PLUGIN_ID;
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources =
                new TestResourceInfo[] {
                        new TestResourceInfo(
                                "resources/XpathBrokenMappingsValidationTest", "BrokenMappingsTest/Process Packages{processes}/XPathBrokenMapping.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
                        new TestResourceInfo(
                                "resources/XpathBrokenMappingsValidationTest", "BrokenMappingsTest/Service Descriptors{wsdl}/WSDLCreatingPackage.wsdl"), //$NON-NLS-1$ //$NON-NLS-2$
                };

        return testResources;
    }

}
