/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.n2.wsdlgen.test;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;

/**
 * AbsoluteURINotAllowedTest
 * <p>
 * AbsoluteURINotAllowedTest - Test selected validations are correctly raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 * 
 * 
 * 
 * @author
 * @since
 */
public class N2_05_AbsoluteURINotAllowedTest extends AbstractN2BaseValidationTest {

    public N2_05_AbsoluteURINotAllowedTest() {
        super(true);
    }

    /**
     * AbsoluteURINotAllowedTest
     * 
     * @throws Exception
     */
    public void testAbsoluteURINotAllowedTest() throws Exception {
        doTestValidations();
        return;
    }

    @Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos =
                new ValidationsTestProblemMarkerInfo[] {

                        new ValidationsTestProblemMarkerInfo(
                                "/project8/Service Descriptors/Copy of Profile_WSDLEmbedsSchema1_Schema1IncludeSchema2L.wsdl", //$NON-NLS-1$ 
                                "cds.wsdlbom.absolutePathInvalid", //$NON-NLS-1$ 
                                "//@eTypes/@eExtensibilityElements.0/@schema/XSDInclude", //$NON-NLS-1$ 
                                "WSDL 1.1 : WSDLs may not refer to absolute URIs (http://www.amsbqa.com/linda08/WSDLEmbedSchema1/Schema1IncludeSchema2)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                        new ValidationsTestProblemMarkerInfo(
                                "/project8/Service Descriptors/Copy of Profile_WSDLEmbedsSchema1_Schema1IncludeSchema2L.wsdl", //$NON-NLS-1$ 
                                "wsdltobom.absoluteSchemaLocInvalid", //$NON-NLS-1$ 
                                "//@eTypes/@eExtensibilityElements.0/@schema/XSDInclude", //$NON-NLS-1$ 
                                "WSDL 1.1 : WSDL containing absolute URI to XSD cannot be converted to business object model. (http://www.amsbqa.com/linda08/WSDLEmbedSchema1/Schema1IncludeSchema2)", //$NON-NLS-1$ 
                                ""), //$NON-NLS-1$ 

                };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "AbsoluteURINotAllowedTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.n2.wsdlgen.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources =
                new TestResourceInfo[] {
                        new TestResourceInfo(
                                "resources/AbsoluteURINotAllowedTest", "project8/Service Descriptors{wsdl}/AirlineUserProfileL.xsd"), //$NON-NLS-1$ //$NON-NLS-2$
                        new TestResourceInfo(
                                "resources/AbsoluteURINotAllowedTest", "project8/Service Descriptors{wsdl}/Copy of Profile_WSDLEmbedsSchema1_Schema1IncludeSchema2L.wsdl"), //$NON-NLS-1$ //$NON-NLS-2$
                };

        return testResources;
    }

}
